import {operations as operationSchemas, validateSchema} from '../../../backend/contract.mjs'
// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-contract.mjs. Do not edit.
export type UUID = string
export type Date = string
export type Notes = { "type": "doc"; [key: string]: unknown }
export type Schedule = { "date": string; "time": string; "timezone": string; "offsetMinutes"?: number }
export type PreferredTime = { "text": string; "status"?: "validated" | "context_required" | "ambiguous"; "interpretation"?: { "kind": "daypart" | "relative" | "clock" | "unresolved"; "value"?: string } }
export type RecurrenceIntent = { "text": string; "status"?: "validated" | "ambiguous"; "kind"?: "fixed" | "flexible" | "unresolved"; "weekdays"?: Array<number>; "intervalWeeks"?: number; "anchorDate": string; "frequency"?: number; "period"?: "week"; "preferredWeekdays"?: Array<number> }
export type Reference = { "id": string; "label": string; "url": string }
export type Error = { "error": { "code": "validation" | "unauthenticated" | "expired" | "forbidden" | "conflict" | "not_found" | "unavailable" | "invalid_response"; "message": string; "details"?: { [key: string]: unknown } } }
export type Task = { "id": string; "title": string; "notes": Notes; "location"?: string; "durationIntent"?: string; "actualDurationMinutes"?: number; "completed": boolean; "priority": "none" | "low" | "medium" | "high"; "projectId"?: string; "schedule"?: Schedule; "durationMinutes"?: number; "archived"?: boolean; "references"?: Array<Reference>; "preferredTime"?: PreferredTime }
export type Routine = { "id": string; "title": string; "notes": Notes; "location"?: string; "durationIntent"?: string; "actualDurationMinutes"?: number; "weekdays": Array<number>; "time"?: string; "timezone": string; "durationMinutes"?: number; "archived"?: boolean; "preferredTime"?: PreferredTime; "recurrenceIntent"?: RecurrenceIntent }
export type Occurrence = { "id": string; "title"?: string; "notes"?: Notes; "location"?: string; "durationIntent"?: string; "actualDurationMinutes"?: number; "routineId": string; "date": string; "completed": boolean; "schedule"?: Schedule; "durationMinutes"?: number; "preferredTime"?: PreferredTime; "skipped"?: boolean; "edited"?: boolean; "templateRevision"?: number }
export type Project = { "id": string; "title": string; "notes": Notes; "completed"?: boolean; "archived"?: boolean; "targetDate"?: string; "references"?: Array<Reference> }
export type Period = { "start": string; "end": string }
export type Outcome = { "id": string; "taskId": string; "period": Period; "position": number }
export type PeriodNote = { "id": string; "kind": "day" | "week"; "period": Period; "notes": Notes }
export type Preferences = { "timezone": string; "weekStartsOn": number; "weather": { "enabled": boolean; "source": "latest" | "manual"; "units": "celsius" | "fahrenheit"; "manual"?: { "latitude": number; "longitude": number; "label"?: string } } }
export type TaskEnvelope = { "value": Task; "revision": number; "createdAt": string; "updatedAt": string }
export type RoutineEnvelope = { "value": Routine; "revision": number; "createdAt": string; "updatedAt": string }
export type OccurrenceEnvelope = { "value": Occurrence; "revision": number; "createdAt": string; "updatedAt": string }
export type ProjectEnvelope = { "value": Project; "revision": number; "createdAt": string; "updatedAt": string }
export type OutcomeEnvelope = { "value": Outcome; "revision": number; "createdAt": string; "updatedAt": string }
export type PeriodNoteEnvelope = { "value": PeriodNote; "revision": number; "createdAt": string; "updatedAt": string }
export type PreferencesEnvelope = { "value": Preferences; "revision": number; "createdAt": string; "updatedAt": string }
export type CalendarEvent = { "id": string; "role": "primary" | "managed"; "etag": string; "summary": string; "location": string; "description": string; "start"?: { "date"?: string; "dateTime"?: string; "timeZone"?: string }; "end"?: { "date"?: string; "dateTime"?: string; "timeZone"?: string }; "linked": boolean; "recurring": boolean }
export type CalendarDraft = { "id": string; "state": "pending" | "error" | "conflict" | "superseded"; "operation": "create" | "update" | "delete"; "event"?: { "summary": string; "location": string; "description": string; "start": { "date"?: string; "dateTime"?: string; "timeZone"?: string }; "end": { "date"?: string; "dateTime"?: string; "timeZone"?: string } } }
export type CalendarConflict = { "id": string; "kind"?: "tasks" | "occurrences"; "title": string; "reason": string }
export type CalendarCacheMetadata = { "available": boolean; "state": "connected" | "connecting" | "disconnected" | "needs_consent" | "unavailable"; "syncActive": boolean; "lastSyncAt": number | null; "plannerLastSyncAt": number | null; "windowStart": string | null; "windowEnd": string | null }
export type CalendarCache = { "id": "calendar"; "items": Array<CalendarEvent>; "available": boolean; "state": "connected" | "connecting" | "disconnected" | "needs_consent" | "unavailable"; "syncActive": boolean; "lastSyncAt": number | null; "plannerLastSyncAt": number | null; "windowStart": string | null; "windowEnd": string | null; "generation"?: string; "sequence": number; "status": "fresh" | "stale" | "unavailable"; "drafts": Array<CalendarDraft>; "planner": { "plannerLastSyncAt": number | null; "conflicts": Array<CalendarConflict> } }
export type Weather = { "status": "fresh" | "stale" | "unavailable"; "units": "celsius" | "fahrenheit"; "timezone": string; "attribution": { "url": "https://open-meteo.com/"; "label": string }; "hourly": Array<{ "at": string; "temperature": number; "rainProbability": number; "windSpeed": number }>; "daily": Array<{ "date": Date; "minimum": number; "maximum": number; "rainProbability": number }>; "current"?: { "at": string; "temperature": number; "rainProbability": number; "windSpeed": number }; "location"?: { "latitude": number; "longitude": number; "label"?: string; "source": "bridge" | "manual"; "observedAt": string }; "fetchedAt"?: string; "expiresAt"?: string }
export type Operations = {
 search: { input: { "query": string; "mode"?: "keyword" | "hybrid"; "kinds"?: Array<"tasks" | "projects" | "routines" | "occurrences" | "periodNotes">; "includeArchived"?: boolean; "limit"?: number }; output: { "items": Array<{ "kind": "tasks" | "projects" | "routines" | "occurrences" | "periodNotes"; "id": string; "revision": number; "title": string; "excerpt": string; "score": number }>; "semantic": "disabled" | "pending" | "ready"; "pendingDocuments": number; "retryAfterMs"?: number; "queryJob"?: { "id": number; "revision": number; "text": string; "attempt": number; "type": "document" | "query"; "model": string; "dimensions": number; "indexVersion": string; "inputVersion": string; "inputHash": string; "source"?: { "kind": "tasks" | "projects" | "routines" | "occurrences" | "periodNotes"; "id": string } } } }
 search_index_status: { input: {  }; output: { "enabled": boolean; "model": "text-embedding-3-small"; "dimensions": 1536; "pending": number } }
 configure_search: { input: { "enabled": boolean }; output: { "enabled": boolean; "model": "text-embedding-3-small"; "dimensions": 1536 } }
 search_index_batch: { input: { "limit"?: number; "id"?: number; "source"?: { "kind": "tasks" | "projects" | "routines" | "occurrences" | "periodNotes"; "id": string } }; output: { "items": Array<{ "id": number; "revision": number; "text": string; "attempt": number; "type": "document" | "query"; "model": string; "dimensions": number; "indexVersion": string; "inputVersion": string; "inputHash": string; "source"?: { "kind": "tasks" | "projects" | "routines" | "occurrences" | "periodNotes"; "id": string } }>; "enabled": boolean; "model": "text-embedding-3-small"; "dimensions": 1536 } }
 search_index_commit: { input: { "id": number; "revision": number; "model": string; "dimensions": number; "indexVersion": string; "inputVersion": string; "inputHash": string; "embedding": Array<number> }; output: { "accepted": boolean } }
 search_query_commit: { input: { "id": number; "revision": number; "model": string; "dimensions": number; "indexVersion": string; "inputVersion": string; "inputHash": string; "embedding": Array<number> }; output: { "accepted": boolean } }
 calendar_cache_publish: { input: { "sequence": number; "generation": string; "page": number; "pages": number; "items": Array<CalendarEvent>; "drafts": Array<CalendarDraft>; "conflicts": Array<CalendarConflict>; "metadata"?: CalendarCacheMetadata }; output: { "sequence": number; "committed": boolean } }
 list_calendar_events: { input: { "period": Period; "timezone": string; "cursor"?: string; "limit"?: number }; output: { "available": boolean; "state": "connected" | "connecting" | "disconnected" | "needs_consent" | "unavailable"; "syncActive": boolean; "lastSyncAt": number | null; "plannerLastSyncAt": number | null; "windowStart": string | null; "windowEnd": string | null; "generation"?: string; "sequence": number; "status": "fresh" | "stale" | "unavailable"; "drafts": Array<CalendarDraft>; "planner": { "plannerLastSyncAt": number | null; "conflicts": Array<CalendarConflict> }; "items": Array<CalendarEvent>; "nextCursor"?: string } }
 get_current: { input: { "kind": "tasks" | "occurrences"; "id": string }; output: { "record": TaskEnvelope | OccurrenceEnvelope | null; "deleted": boolean; "revision": number; "scheduledAt": string | null } }
 get_command_receipt: { input: { "key": string }; output: { "found": boolean; "operation"?: string; "input"?: {  }; "result"?: {  } } }
 calendar_inventory: { input: { "kind": "tasks" | "occurrences" | "routines"; "cursor"?: string }; output: { "items": Array<TaskEnvelope | OccurrenceEnvelope | RoutineEnvelope>; "nextCursor"?: string } }
 calendar_changes: { input: { "cursor": number }; output: { "items": Array<{ "sequence": number; "kind": "tasks" | "occurrences"; "id": string; "revision": number; "deleted": boolean }>; "cursor": number } }
 calendar_current: { input: { "kind": "tasks" | "occurrences"; "id": string }; output: { "record": TaskEnvelope | OccurrenceEnvelope | null; "deleted": boolean; "revision": number } }
 calendar_apply: { input: { "kind": "tasks" | "occurrences"; "id": string; "expectedRevision": number; "schedule": Schedule | null; "title"?: string; "location"?: string; "notes"?: Notes; "durationMinutes"?: number; "idempotencyKey": string }; output: TaskEnvelope | OccurrenceEnvelope }
 calendar_materialize: { input: { "routineId": string; "through": string; "ids": { [key: string]: string }; "idempotencyKey": string }; output: { "items": Array<OccurrenceEnvelope> } }
 list_agenda: { input: { "date": string; "timezone": string }; output: { "items": Array<{ "kind": "tasks" | "occurrences"; "value": Task | Occurrence; "revision": number; "createdAt": string; "updatedAt": string; "scheduledAt": string }> } }
 create_task: { input: { "value": Task; "idempotencyKey": string }; output: TaskEnvelope }
 update_routine: { input: { "value": Routine; "expectedRevision": number; "idempotencyKey": string }; output: RoutineEnvelope }
 move_occurrence: { input: { "id": string; "expectedRevision": number; "idempotencyKey": string; "schedule": Schedule | null; "location"?: string; "durationIntent"?: string; "actualDurationMinutes"?: number; "title"?: string; "notes"?: Notes; "durationMinutes"?: number; "skipped"?: boolean }; output: OccurrenceEnvelope }
 complete_occurrence: { input: { "id": string; "expectedRevision": number; "idempotencyKey": string; "completed": boolean }; output: OccurrenceEnvelope }
 preview_schedule: { input: { "changes": Array<{ "kind": "tasks" | "occurrences"; "id": string; "expectedRevision": number; "schedule": Schedule | null }> }; output: { "items": Array<TaskEnvelope | OccurrenceEnvelope>; "applied": boolean } }
 apply_schedule: { input: { "changes": Array<{ "kind": "tasks" | "occurrences"; "id": string; "expectedRevision": number; "schedule": Schedule | null }>; "idempotencyKey": string }; output: { "items": Array<TaskEnvelope | OccurrenceEnvelope>; "applied": boolean } }
 materialize_routine: { input: { "routineId": string; "through": string; "ids": { [key: string]: string }; "idempotencyKey": string }; output: { "items": Array<OccurrenceEnvelope> } }
 delete_task: { input: { "id": string; "expectedRevision": number; "idempotencyKey": string }; output: { "deleted": true; "id": string } }
 bind_external_event: { input: { "kind": "tasks" | "occurrences"; "entityId": string; "expectedRevision": number; "provider": string; "calendarId": string; "eventId": string; "remoteRevision": string; "expectedRemoteRevision"?: string; "idempotencyKey": string }; output: { "bound": true } }
}

export interface ApplicationTransport {
 request<T>(path: string, decode: (value: unknown) => T, options: { method?: 'GET'|'POST'|'PUT'|'DELETE'; body?: unknown; signal?: AbortSignal }): Promise<T>
}
/** Inject the existing JsonTransport: preserves CSRF, logout fencing and redirect rejection. */
export class ApplicationClient {
 private readonly http: ApplicationTransport
 constructor(http: ApplicationTransport) { this.http = http }
 call<K extends keyof Operations>(operation: K, input: Operations[K]['input'], signal?: AbortSignal): Promise<Operations[K]['output']> {
  validateSchema(operationSchemas[operation].input, input)
  return this.http.request('/operations/' + operation, value => {
   validateSchema(operationSchemas[operation].output, value)
   return value as Operations[K]['output']
  }, { method: 'POST', body: input, signal })
 }
}
