// SPDX-License-Identifier: Apache-2.0
import {useEffect,useState} from 'react'
import {transport} from '../lib/backend/session'
import {getConfig} from '../lib/config'
import {usePlannerClock} from '../lib/planner-clock'
import type {DatePeriod} from '../lib/dates'
type Event={id:string;role:'primary'|'managed';etag:string;summary:string;location:string;description:string;start?:{dateTime?:string;date?:string};end?:{dateTime?:string;date?:string};recurring:boolean}
type Draft={id:string;state:string;operation:string;event?:Event}
type Collection={items:Event[];drafts:Draft[]}
const decode=(v:unknown)=>{const c=v as Collection;if(!c||!Array.isArray(c.items)||!Array.isArray(c.drafts))throw Error('Invalid Calendar response');return c}
export function CalendarAgenda({period}:{period:DatePeriod}){
 const clock=usePlannerClock(),[data,setData]=useState<Collection>({items:[],drafts:[]}),[error,setError]=useState(''),[editing,setEditing]=useState<Event|null>(null),[busy,setBusy]=useState(false)
 const day=(value:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:clock.preferences.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))
 async function refresh(){setData(await transport.request('/calendar/events',decode))}
 useEffect(()=>{if(getConfig().demo)return;let live=true;const controller=new AbortController();async function load(){try{const c=await transport.request('/calendar/events',decode,{signal:controller.signal});if(live){setData(c);setError('')}}catch{if(live)setError('Calendar is unavailable.')}}void load();const timer=setInterval(()=>void load(),15000);return()=>{live=false;controller.abort();clearInterval(timer)}},[])
 if(getConfig().demo)return null
 const items=data.items.filter(e=>{const date=e.start?.date??(e.start?.dateTime?day(e.start.dateTime):'');return date>=period.start&&date<=period.end}).sort((a,b)=>(a.start?.dateTime??a.start?.date??'').localeCompare(b.start?.dateTime??b.start?.date??''))
 async function mutate(operation:string,event:Event){setBusy(true);setError('');try{await transport.request('/calendar/editEvent',v=>v,{method:'POST',body:{operation,role:'managed',id:event.id,etag:event.etag,event}});setEditing(null);await refresh()}catch{setError('Could not save this change. Refresh and retry; your draft is retained.')}finally{setBusy(false)}}
 const local=(value?:string)=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
 return <section aria-label="Google Calendar events"><div className="section-heading"><h2>Calendar</h2><button onClick={()=>{const start=new Date();start.setSeconds(0,0);setEditing({id:'',role:'managed',etag:'',summary:'',location:'',description:'',start:{dateTime:start.toISOString()},end:{dateTime:new Date(start.getTime()+3600000).toISOString()},recurring:false})}}>New calendar event</button></div>{items.map(e=><article className="routine-row" key={e.role+e.id}><span className="time">{e.start?.date?'All day':e.start?.dateTime?new Intl.DateTimeFormat('en',{timeZone:clock.preferences.timezone,hour:'numeric',minute:'2-digit'}).format(new Date(e.start.dateTime)):''}</span><div><h3>{e.summary}</h3><p>{e.location}</p><p className="muted">{e.role==='primary'?'Primary · read-only':'MeOS calendar'}{e.recurring?' · recurring':''}</p>{e.role==='managed'&&e.start?.dateTime&&<button disabled={data.drafts.some(d=>d.id===e.id)} onClick={()=>setEditing(e)}>Edit calendar event</button>}</div></article>)}{!items.length&&<p className="muted">No calendar events in this period.</p>}{data.drafts.map(d=><p key={d.id} role="status">{d.state==='conflict'?'Conflict: Google changed this event. Your local draft is preserved.':'Calendar change queued for the next sync.'} {d.event?.summary}{d.state==='conflict'&&<button disabled={busy} onClick={()=>void mutate('discard',{id:d.id} as Event)}>Keep Google version</button>}</p>)}{editing&&<form className="settings-card" onSubmit={e=>{e.preventDefault();void mutate(editing.id?'update':'create',editing)}}><h3>{editing.id?'Edit':'New'} calendar event</h3><label>Event title<input required value={editing.summary} maxLength={300} onChange={e=>setEditing({...editing,summary:e.target.value})}/></label><label>Location<input value={editing.location} maxLength={1000} onChange={e=>setEditing({...editing,location:e.target.value})}/></label><p className="muted">Times below use this device’s timezone.</p><label>Starts<input required type="datetime-local" value={local(editing.start?.dateTime)} onChange={e=>{if(e.target.value)setEditing({...editing,start:{dateTime:new Date(e.target.value).toISOString()}})}}/></label><label>Ends<input required type="datetime-local" value={local(editing.end?.dateTime)} onChange={e=>{if(e.target.value)setEditing({...editing,end:{dateTime:new Date(e.target.value).toISOString()}})}}/></label><label>Description<textarea value={editing.description} maxLength={10000} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><button disabled={busy}>Save calendar event</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button>{editing.id&&<button type="button" disabled={busy} onClick={()=>{if(window.confirm('Delete this event from the MeOS calendar?'))void mutate('delete',editing)}}>Delete calendar event</button>}</form>}{error&&<p role="alert">{error}</p>}</section>
}
