// SPDX-License-Identifier: Apache-2.0
import {useEffect,useRef,useState,type ReactNode} from 'react'
import {transport} from '../lib/backend/session'
import {queryClient} from '../lib/store'
import {getConfig} from '../lib/config'
import {usePlannerClock} from '../lib/planner-clock'
import {calendarEventOverlaps, type DatePeriod} from '../lib/dates'
type Event={id:string;role:'primary'|'managed';etag:string;summary:string;location:string;description:string;start?:{dateTime?:string;date?:string};end?:{dateTime?:string;date?:string};recurring:boolean;linked?:boolean}
type Draft={id:string;state:string;operation:string;event?:Event}
type Collection={items:Event[];drafts:Draft[];planner?:{plannerLastSyncAt:number|null;conflicts:Array<{id:string;title:string;reason:string}>}}
const decode=(v:unknown)=>{const c=v as Collection;if(!c||!Array.isArray(c.items)||!Array.isArray(c.drafts))throw Error('Invalid Calendar response');return c}
export type CalendarTimelineItem={key:string;instant:number;content:ReactNode}
export function CalendarAgenda({period,showChrome=true,children}:{period:DatePeriod;showChrome?:boolean;children?:(items:CalendarTimelineItem[])=>ReactNode}){
 const lastSync=useRef<number|null|undefined>(undefined)
 const clock=usePlannerClock(),[data,setData]=useState<Collection>({items:[],drafts:[]}),[error,setError]=useState(''),[editing,setEditing]=useState<Event|null>(null),[busy,setBusy]=useState(false)
 async function refresh(){setData(await transport.request('/calendar/events',decode))}
 useEffect(()=>{if(getConfig().demo)return;let live=true;const controller=new AbortController();async function load(){try{const c=await transport.request('/calendar/events',decode,{signal:controller.signal});if(live){if(c.planner?.plannerLastSyncAt!==lastSync.current){lastSync.current=c.planner?.plannerLastSyncAt;void queryClient.invalidateQueries({queryKey:['tasks']});void queryClient.invalidateQueries({queryKey:['occurrences']})}setData(c);setError('')}}catch{if(live)setError('Calendar is unavailable.')}}void load();const timer=setInterval(()=>void load(),15000);return()=>{live=false;controller.abort();clearInterval(timer)}},[])
 const items=data.items.filter(e=>!e.linked).filter(e=>showChrome||!e.start?.date).filter(e=>calendarEventOverlaps(e,period,clock.preferences.timezone)).sort((a,b)=>Date.parse(a.start?.dateTime??a.start?.date??'')-Date.parse(b.start?.dateTime??b.start?.date??''))
 async function mutate(operation:string,event:Event){setBusy(true);setError('');try{await transport.request('/calendar/editEvent',v=>v,{method:'POST',body:{operation,role:'managed',id:event.id,etag:event.etag,event}});setEditing(null);await refresh()}catch{setError('Could not save this change. Refresh and retry; your draft is retained.')}finally{setBusy(false)}}
 const local=(value?:string)=>{if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
 const eventRow=(e:Event)=><article className="routine-row agenda-row" key={`calendar:${e.role}:${e.id}`}><span className="time">{e.start?.date?'All day':e.start?.dateTime?new Intl.DateTimeFormat('en',{timeZone:clock.preferences.timezone,hour:'numeric',minute:'2-digit'}).format(new Date(e.start.dateTime)):''}</span><div><h3>{e.summary}</h3><p>{e.location}</p><p className="muted">{e.role==='primary'?'Primary':'MeOS calendar'}</p>{e.role==='managed'&&e.start?.dateTime&&<button disabled={data.drafts.some(d=>d.id===e.id&&d.state!=='superseded')} onClick={()=>setEditing(e)}>Edit calendar event</button>}</div></article>
 if(getConfig().demo)return children?<>{children([])}</>:null
 return <>{children?children(items.filter(e=>e.start?.dateTime).map(e=>({key:`calendar:${e.role}:${e.id}`,instant:Date.parse(e.start!.dateTime!),content:eventRow(e)}))):<section aria-label="Google Calendar events">{showChrome&&<div className="section-heading"><h2>Calendar</h2><button onClick={()=>{const start=new Date();start.setSeconds(0,0);setEditing({id:'',role:'managed',etag:'',summary:'',location:'',description:'',start:{dateTime:start.toISOString()},end:{dateTime:new Date(start.getTime()+3600000).toISOString()},recurring:false})}}>New calendar event</button></div>}{items.map(eventRow)}{showChrome&&!items.length&&<p className="muted">No calendar events in this period.</p>}</section>}{data.planner?.conflicts.map(c=><p role="alert" key={c.id}>{c.title}: {c.reason}</p>)}{data.drafts.map(d=><p key={d.id} role="status">{d.state==='error'?'Google rejected this change. Your draft is preserved; retry after correcting permissions or discard it.':d.state==='superseded'?'Google version kept. Your displaced local draft is preserved.':d.state==='conflict'?'Connection changed. Your local draft is preserved.':'Calendar change queued for the next sync.'} {d.event?.summary}{d.state==='error'&&<button disabled={busy} onClick={()=>void mutate('retry',{id:d.id} as Event)}>Retry change</button>}{(d.state==='conflict'||d.state==='error'||d.state==='superseded')&&<button disabled={busy} onClick={()=>void mutate('discard',{id:d.id} as Event)}>{d.state==='superseded'?'Dismiss saved draft':'Discard draft'}</button>}</p>)}{editing&&<form className="settings-card" onSubmit={e=>{e.preventDefault();void mutate(editing.id?'update':'create',editing)}}><h3>{editing.id?'Edit':'New'} calendar event</h3><label>Event title<input required value={editing.summary} maxLength={300} onChange={e=>setEditing({...editing,summary:e.target.value})}/></label><label>Location<input value={editing.location} maxLength={1000} onChange={e=>setEditing({...editing,location:e.target.value})}/></label><p className="muted">Times below use this device’s timezone.</p><label>Starts<input required type="datetime-local" value={local(editing.start?.dateTime)} onChange={e=>{if(e.target.value)setEditing({...editing,start:{dateTime:new Date(e.target.value).toISOString()}})}}/></label><label>Ends<input required type="datetime-local" value={local(editing.end?.dateTime)} onChange={e=>{if(e.target.value)setEditing({...editing,end:{dateTime:new Date(e.target.value).toISOString()}})}}/></label><label>Description<textarea value={editing.description} maxLength={10000} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><button disabled={busy}>Save calendar event</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button>{editing.id&&<button type="button" disabled={busy} onClick={()=>{if(window.confirm('Delete this event from the MeOS calendar?'))void mutate('delete',editing)}}>Delete calendar event</button>}</form>}{error&&<p role="alert">{error}</p>}</>
}
