// SPDX-License-Identifier: Apache-2.0
import {useEffect,useState} from 'react'
import {transport} from '../lib/backend/session'
import {getConfig} from '../lib/config'
type Status={state:string;syncActive:boolean;syncError?:'session_expired'|'retrying'|null}
const decode=(value:unknown):Status=>{const v=value as Status;if(!v||!['unconfigured','disconnected','connecting','connected','needs_consent','error'].includes(v.state)||typeof v.syncActive!=='boolean')throw Error('Invalid Calendar status');return v}
export function CalendarSettings(){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(getConfig().demo)return;let active=true;const controller=new AbortController();async function refresh(){try{const s=await transport.request('/calendar/status',decode,{signal:controller.signal});if(active){setStatus(s);setError('')}}catch{if(active)setError('Calendar status is unavailable.')}}void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>{active=false;controller.abort();clearInterval(timer)}},[])
 if(getConfig().demo)return null
 async function connect(){setBusy(true);setError('');try{const url=await transport.request('/calendar/connect',v=>{const u=new URL((v as {authorizationUrl:string}).authorizationUrl);if(u.origin!=='https://accounts.google.com'||u.pathname!=='/o/oauth2/v2/auth'||u.username||u.password||u.hash)throw Error('Invalid authorization URL');return u.href},{method:'POST'});window.location.assign(url)}catch{setError('Could not start Calendar connection. Please retry.');setBusy(false)}}
 async function disconnect(){setBusy(true);setError('');try{await transport.request('/calendar/disconnect',v=>{if((v as {state:string}).state!=='disconnected')throw Error('Invalid response');return v},{method:'POST'});setStatus({state:'disconnected',syncActive:false})}catch{setError('Could not disconnect Calendar. Please retry.')}finally{setBusy(false)}}
 return <section className="settings-card"><h2>Google Calendar</h2><p>Import your primary calendar read-only. MeOS uses a separate calendar for two-way syncing of managed events; your other calendars are unchanged.</p><p role="status">{!status?'Checking connection…':status.state==='unconfigured'?'Calendar connection has not been configured.':status.state==='connected'?(status.syncError==='session_expired'?'Calendar sync needs a server-side session repair. Your Google connection is unchanged.':status.syncError==='retrying'?'Calendar sync is delayed; retrying automatically.':status.syncActive?'Connected · checks for updates every minute.':'Connected · sync initialization pending.') :status.state==='needs_consent'?'Reconnect Google Calendar to continue.':'Not connected.'}</p>{status&&status.state!=='unconfigured'&&(status.state==='connected'?<button disabled={busy} onClick={()=>void disconnect()}>Disconnect Calendar</button>:<button className="primary" disabled={busy} onClick={()=>void connect()}>Connect Google Calendar</button>)}<p className="muted">Disconnecting retains imported events and MeOS data.</p>{error&&<p role="alert">{error}</p>}</section>
}
