// SPDX-License-Identifier: Apache-2.0
import {useState} from 'react'
import type {Occurrence} from '../lib/contracts'
import {moveOccurrence} from '../lib/backend/ui-repository'
import {queryClient} from '../lib/store'
import {Sheet} from './Planning'
import {NotesEditor} from './NotesEditor'
import {TimezoneSelect} from './TimezoneSelect'
export function OccurrenceEditor({initial,onClose}:{initial:Occurrence;onClose:()=>void}){
 const [title,setTitle]=useState(initial.title??''),[date,setDate]=useState(initial.schedule?.date??''),[time,setTime]=useState(initial.schedule?.time??''),[timezone,setTimezone]=useState(initial.schedule?.timezone??'UTC'),[offset,setOffset]=useState(initial.schedule?.offsetMinutes?.toString()??''),[notes,setNotes]=useState(initial.notes??{type:'doc' as const}),[duration,setDuration]=useState(initial.durationMinutes?.toString()??''),[error,setError]=useState(''),[saving,setSaving]=useState(false)
 return <Sheet title="Routine instance" onClose={onClose} dirty><form className="resource-form" onSubmit={async e=>{e.preventDefault();setSaving(true);setError('');try{if(!!date!==!!time)throw Error('Both date and time are required, or clear both.');await moveOccurrence(initial,{title,notes,schedule:date?{date,time,timezone,...(offset?{offsetMinutes:Number(offset)}:{})}:null,...(duration?{durationMinutes:Number(duration)}:{})});await queryClient.invalidateQueries({queryKey:['occurrences']});onClose()}catch(e){setError(String(e))}finally{setSaving(false)}}}><div className="resource-body"><p>Only this instance changes. Original routine slot: {initial.date}.</p><label>Instance name<input value={title} required onChange={e=>setTitle(e.target.value)}/></label><label>Instance date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Instance time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><button type="button" onClick={()=>{setDate('');setTime('')}}>Clear instance schedule</button><TimezoneSelect label="Instance timezone" value={timezone} onChange={setTimezone}/><label>UTC offset in minutes (required for repeated DST times)<input type="number" value={offset} onChange={e=>setOffset(e.target.value)}/></label><label>Instance duration<input type="number" required={initial.durationMinutes!==undefined} min="1" max="1440" value={duration} onChange={e=>setDuration(e.target.value)}/></label>{initial.durationMinutes!==undefined&&<p className="muted">Set a duration of 1–1440 minutes; clearing an existing duration is not supported.</p>}<NotesEditor value={notes} onChange={setNotes}/>{initial.preferredTime&&<p>Preferred time: {initial.preferredTime.text} ({initial.preferredTime.status})</p>}{error&&<p role="alert">{error} Your draft is preserved.</p>}</div><button disabled={saving}>Save instance</button></form></Sheet>
}
