import {CalendarAgenda,type CalendarTimelineItem} from './CalendarAgenda'
import {getConfig} from '../lib/config'
import {OccurrenceEditor} from './OccurrenceEditor'
import type {Occurrence} from '../lib/contracts'
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react'
import {useLiveQuery} from '@tanstack/react-db'
import {tasksCollection,routinesCollection,occurrencesCollection,outcomesCollection,periodNotesCollection,queryClient,savePlanner,saveTask,removeOutcome} from '../lib/store'
import {usePlannerClock,projectScheduledTasks,projectRoutineOccurrences} from '../lib/planner-clock'
import {type DatePeriod} from '../lib/dates'
import type {Routine,Task} from '../lib/contracts'
import type {PeriodNote} from '../lib/planner-contracts'
import {TimezoneSelect} from './TimezoneSelect'
import {NotesEditor} from './NotesEditor'
import {TaskRows} from '../components'

const PlanningContext=createContext<{next:boolean;setNext:(v:boolean)=>void;openOutcome:()=>void;openPeriodNote:(note:PeriodNote)=>void}>({next:false,setNext:()=>{},openOutcome:()=>{},openPeriodNote:()=>{}})
export const usePlanning=()=>useContext(PlanningContext)
export function PlanningProvider({children}:{children:ReactNode}) {
 const [next,setNext]=useState(false);const [outcomePeriod,setOutcomePeriod]=useState<DatePeriod|null>(null);const [noteDraft,setNoteDraft]=useState<PeriodNote|null>(null);const clock=usePlannerClock()
 return <PlanningContext.Provider value={{next,setNext,openPeriodNote:setNoteDraft,openOutcome:()=>setOutcomePeriod(Object.freeze({...next?clock.nextWeek:clock.thisWeek}))}}>{children}{outcomePeriod&&<OutcomeEditor period={outcomePeriod} onClose={()=>setOutcomePeriod(null)}/ >}{noteDraft&&<PeriodNoteEditor initial={noteDraft} onClose={()=>setNoteDraft(null)}/>}</PlanningContext.Provider>
}
export function Sheet({title,onClose,dirty=false,children}:{title:string;onClose:()=>void;dirty?:boolean;children:ReactNode}) {
 const ref=useRef<HTMLDialogElement>(null);const backdrop=useRef(false)
 const close=()=>{if(!dirty||window.confirm('Discard unsaved changes?'))onClose()}
 useEffect(()=>{const trigger=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{ref.current?.close();trigger?.focus()}},[])
 function outside(event:React.PointerEvent<HTMLDialogElement>){const r=event.currentTarget.getBoundingClientRect();return event.target===event.currentTarget&&(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)}
 return <dialog ref={ref} className="resource-dialog" aria-label={title} onCancel={e=>{e.preventDefault();close()}} onPointerDown={e=>{backdrop.current=outside(e)}} onPointerUp={e=>{if(backdrop.current&&outside(e))close();backdrop.current=false}}><div className="resource-top"><h2>{title}</h2><button className="quiet-action" onClick={close} aria-label="Close planner details">Close ×</button></div>{children}</dialog>
}
export function PeriodNotesButton({kind,period}:{kind:'day'|'week';period:DatePeriod}) {
 const {data:notes=[],isLoading,isError}=useLiveQuery(q=>q.from({note:periodNotesCollection}));const {openPeriodNote}=usePlanning()
 return <><button className="quiet-action" disabled={isLoading||isError} onClick={()=>{const existing=notes.find(n=>n.kind===kind&&samePeriod(n.period,period));openPeriodNote(existing?{...existing,period:Object.freeze({...existing.period})}:{id:crypto.randomUUID(),kind,period:Object.freeze({...period}),notes:{type:'doc'}})}}>{kind==='day'?'Day':'Week'} Notes <span aria-hidden="true">↗</span></button>{isError&&<span role="alert">Notes unavailable</span>}</>
}
function PeriodNoteEditor({initial,onClose}:{initial:PeriodNote;onClose:()=>void}) {
 const [notes,setNotes]=useState(initial.notes);const [dirty,setDirty]=useState(false);const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 return <Sheet title={`${initial.kind==='day'?'Day':'Week'} Notes`} onClose={onClose} dirty={dirty}><form className="resource-form" onSubmit={async e=>{e.preventDefault();setSaving(true);setError('');try{await savePlanner('period-notes',{...initial,notes});onClose()}catch(e){setError(String(e))}finally{setSaving(false)}}}><div className="resource-body"><p className="muted">{initial.period.start}{initial.kind==='week'?` – ${initial.period.end}`:''}</p><NotesEditor value={notes} onChange={value=>{setNotes(value);setDirty(true)}} label="Period notes"/>{error&&<p role="alert">{error} Your draft is preserved.</p>}</div><div className="resource-actions"><button className="save-button" disabled={saving}>Save notes</button></div></form></Sheet>
}
export const samePeriod=(a:DatePeriod,b:DatePeriod)=>a.start===b.start&&a.end===b.end
export function OutcomeEditor({period,onClose}:{period:DatePeriod;onClose:()=>void}) {
 const {data:tasks=[]}=useLiveQuery(q=>q.from({task:tasksCollection}));const {data:outcomes=[]}=useLiveQuery(q=>q.from({outcome:outcomesCollection}))
 const [taskId,setTaskId]=useState('');const [title,setTitle]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);const created=useRef<Task|null>(null);const taskIdentity=useRef(crypto.randomUUID());const outcomeIdentity=useRef(crypto.randomUUID())
 const eligible=tasks.filter(t=>!t.archived&&!outcomes.some(o=>o.taskId===t.id&&samePeriod(o.period,period)))
 return <Sheet title="Add outcome" onClose={onClose} dirty={!!(taskId||title)}><form className="resource-form" onSubmit={async e=>{e.preventDefault();setError('');setSaving(true);try{
 let id=taskId
 if(!id){if(!title.trim())throw Error('Choose a task or name a new one.');if(!created.current)created.current=await saveTask({id:taskIdentity.current,title,completed:false,priority:'none',notes:{type:'doc'}},true);id=created.current.id}
 await savePlanner('outcomes',{id:outcomeIdentity.current,taskId:id,period,position:outcomes.filter(o=>samePeriod(o.period,period)).length});onClose()
 }catch(e){setError(String(e))}finally{setSaving(false)}}}><div className="resource-body"><p className="muted">{period.start} – {period.end}</p><p className="muted">An outcome links a task to this week. It does not change its priority or scheduled date.</p><label>Choose an existing task<select value={taskId} disabled={saving||!!created.current} onChange={e=>{setTaskId(e.target.value);setTitle('')}}><option value="">Create a new task instead</option>{eligible.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>{!taskId&&<label>New outcome name<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} disabled={saving||!!created.current}/></label>}{created.current&&<p className="muted">Your task has been created. Retry to link it to this week.</p>}{error&&<p role="alert">{error} Your draft is preserved.</p>}</div><div className="resource-actions"><button className="save-button" disabled={saving}>Add to week</button></div></form></Sheet>
}
export function WeeklyOutcomes({period}:{period:DatePeriod}) {
 const {data:tasks=[]}=useLiveQuery(q=>q.from({task:tasksCollection}));const {data:outcomes=[],isLoading,isError}=useLiveQuery(q=>q.from({outcome:outcomesCollection}));const [error,setError]=useState('')
 const rows=outcomes.filter(o=>samePeriod(o.period,period)&&tasks.some(t=>t.id===o.taskId&&!t.archived)).sort((a,b)=>a.position-b.position)
 return <>{isLoading?<p role="status">Gathering outcomes…</p>:isError?<p role="alert">Could not load outcomes.</p>:!rows.length?<p className="empty-state">Choose a few things that would make this week feel good.</p>:rows.map(o=><div className="outcome-row" key={o.id}><TaskRows tasks={[tasks.find(t=>t.id===o.taskId)!]} compact showSchedule/><button className="quiet-action" aria-label={`Remove ${tasks.find(t=>t.id===o.taskId)!.title} from week`} onClick={async()=>{try{await removeOutcome(o.id)}catch(e){setError(String(e))}}}>Remove from week</button></div>)}{error&&<p role="alert">{error}</p>}</>
}
export function PlannerAgenda({period,compact=false}:{period:DatePeriod;compact?:boolean}) {
 const clock=usePlannerClock();const {data:tasks=[],isLoading,isError}=useLiveQuery(q=>q.from({task:tasksCollection}));const {data:routines=[],isError:routineError}=useLiveQuery(q=>q.from({routine:routinesCollection}));const {data:occurrences=[],isError:occurrenceError}=useLiveQuery(q=>q.from({occurrence:occurrencesCollection}));const [error,setError]=useState('')
 const projectedTasks=projectScheduledTasks(tasks,period,clock.preferences.timezone)
 const [selectedInstance,setSelectedInstance]=useState<Occurrence|null>(null)
 useEffect(()=>{if(!getConfig().demo)void queryClient.invalidateQueries({queryKey:['occurrences']})},[clock.today])
 const projectedRoutines=getConfig().demo?projectRoutineOccurrences(routines,occurrences,period,clock.preferences.timezone):projectScheduledTasks(occurrences.filter(o=>!o.skipped),period,clock.preferences.timezone).map(({task:o,displayDate,instant})=>({routine:{...routines.find(r=>r.id===o.routineId)!,title:o.title??'Routine instance',durationMinutes:o.durationMinutes},date:o.date,displayDate,instant,completed:o.completed}))
 const items=[...projectedTasks.map(t=>({...t,kind:'task' as const,key:t.task.id})),...projectedRoutines.map(r=>({...r,kind:'routine' as const,key:r.routine.id+r.date}))].sort((a,b)=>a.displayDate.localeCompare(b.displayDate)||(a.instant??-Infinity)-(b.instant??-Infinity))
 if(isLoading)return <p role="status">Gathering your day…</p>
 if(isError||routineError||occurrenceError)return <p role="alert">Could not load the planner. Please reload to try again.</p>
 const completed=items.filter(item=>item.kind==='task'&&item.task.completed)
 const active=compact?items.filter(item=>item.kind!=='task'||!item.task.completed):items
 const row=(item:typeof items[number])=><div className="routine-row agenda-row" key={item.key}><span className="time">{item.instant===undefined?'Anytime':new Intl.DateTimeFormat('en-GB',{timeZone:clock.preferences.timezone,hour:'2-digit',minute:'2-digit',hour12:clock.preferences.timeFormat==='12-hour'}).format(item.instant)}</span><div>{item.kind==='task'?<TaskRows tasks={[item.task]} compact={compact} onError={setError}/>:<div className="routine-card routine-live"><button className="check" aria-label={`${item.completed?'Reopen':'Complete'} ${item.routine.title} on ${item.date}`} aria-pressed={item.completed} onClick={async()=>{try{const existing=occurrences.find(o=>o.routineId===item.routine.id&&o.date===item.date);await savePlanner('occurrences',{...existing,id:existing?.id??crypto.randomUUID(),routineId:item.routine.id,date:item.date,completed:!item.completed})}catch(e){setError(String(e))}}}>{item.completed?'✓':'○'}</button><div><h2 onClick={()=>{if(!getConfig().demo)setSelectedInstance(occurrences.find(o=>o.routineId===item.routine.id&&o.date===item.date)!)}} className={item.completed?'done':''}>{getConfig().demo?item.routine.title:<button className="quiet-action" aria-label={`Edit instance ${item.routine.title}`}>{item.routine.title}</button>}</h2><p>{item.routine.durationMinutes?`${item.routine.durationMinutes} min · `:''}Routine{item.date!==item.displayDate?` · ${item.date} in ${item.routine.timezone}`:''}</p></div></div>}</div></div>
 const agenda=(calendarItems:CalendarTimelineItem[]=[],calendarAvailable=true)=>{
 const timeline=[...active.map(item=>({key:item.key,displayDate:item.displayDate,instant:item.instant,content:row(item)})),...calendarItems.map(item=>({...item,displayDate:new Intl.DateTimeFormat('en-CA',{timeZone:clock.preferences.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(item.instant)}))].sort((a,b)=>a.displayDate.localeCompare(b.displayDate)||(a.instant??-Infinity)-(b.instant??-Infinity))
 return <>{selectedInstance&&<OccurrenceEditor initial={selectedInstance} onClose={()=>setSelectedInstance(null)}/ >}{compact&&<p className="agenda-progress">{completed.length} of {projectedTasks.length} tasks completed</p>}<section className="timeline" aria-label="Scheduled agenda">{timeline.map(item=>item.content)}{!items.length&&!calendarItems.length&&calendarAvailable&&<div className="open-time"><span className="time">Open</span><div><h2>A little breathing room</h2><p>Nothing scheduled. Leave it open.</p></div></div>}</section>{compact&&completed.length>0&&<details className="completed-tasks"><summary>Completed tasks ({completed.length})</summary>{completed.map(row)}</details>}{error&&<p role="alert">{error}</p>}</>
 }
 return compact?<CalendarAgenda period={period} showChrome={false}>{agenda}</CalendarAgenda>:<><CalendarAgenda period={period}/>{agenda()}</>

}
export function RoutineManager() {
 const clock=usePlannerClock();const {data:routines=[],isLoading,isError}=useLiveQuery(q=>q.from({routine:routinesCollection}));const [selected,setSelected]=useState<Routine|null>(null);const {data:instances=[]}=useLiveQuery(q=>q.from({instance:occurrencesCollection}));const [instance,setInstance]=useState<Occurrence|null>(null)
 return <>{instance&&<OccurrenceEditor initial={instance} onClose={()=>setInstance(null)}/ >}{!getConfig().demo&&<details><summary>Unscheduled routine instances</summary>{instances.filter(o=>!o.schedule&&!o.skipped).map(o=><button key={o.id} className="resource-link" onClick={()=>setInstance(o)}>{o.title} · {o.date}</button>)}</details>}<div className="section-heading"><h2>Routines</h2><button className="quiet-action" onClick={()=>setSelected({id:crypto.randomUUID(),title:'',weekdays:[1,2,3,4,5],timezone:clock.preferences.timezone,notes:{type:'doc'}})}>New routine</button></div>{isLoading&&<p role="status">Gathering routines…</p>}{isError&&<p role="alert">Could not load routines.</p>}{!isLoading&&!isError&&!routines.some(r=>!r.archived)&&<p className="empty-state">Make room for a small daily rhythm.</p>}{routines.filter(r=>!r.archived).map(r=><button key={r.id} className="routine-card routine-edit" onClick={()=>setSelected(r)}><strong>{r.title}</strong><span>{r.time??'Unscheduled'} · {r.recurrenceIntent?.text??r.weekdays.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')}</span></button>)}<details><summary>Archived routines</summary>{routines.filter(r=>r.archived).map(r=><button key={r.id} className="resource-link" onClick={()=>setSelected(r)}>{r.title}</button>)}</details>{selected&&<RoutineEditor initial={selected} onClose={()=>setSelected(null)}/>}</>
}
function RoutineEditor({initial,onClose}:{initial:Routine;onClose:()=>void}) {
 const [draft,setDraft]=useState(initial);const [dirty,setDirty]=useState(false);const [error,setError]=useState('');const [saving,setSaving]=useState(false)
 const update=(part:Partial<Routine>)=>{setDraft(d=>({...d,...part}));setDirty(true)}
 async function save(value:Routine){setSaving(true);setError('');try{await savePlanner('routines',value);onClose()}catch(e){setError(String(e))}finally{setSaving(false)}}
 return <Sheet title="Routine details" onClose={onClose} dirty={dirty}><form className="resource-form" onSubmit={e=>{e.preventDefault();void save(draft)}}><div className="resource-body"><label>Routine name<input value={draft.title} required maxLength={200} onChange={e=>update({title:e.target.value})}/></label>{draft.recurrenceIntent&&<p>Recurrence: {draft.recurrenceIntent.text} ({draft.recurrenceIntent.status}). Changing weekdays replaces this recurrence with a weekly rule.</p>}<fieldset className="weekday-options"><legend>Repeats on</legend>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><label key={day}><input type="checkbox" checked={draft.weekdays.includes(i)} onChange={e=>update({recurrenceIntent:undefined,weekdays:e.target.checked?[...draft.weekdays,i].sort():draft.weekdays.filter(d=>d!==i)})}/>{day}</label>)}</fieldset><div className="plan-fields"><label>Routine time<input type="time" value={draft.time??''} onChange={e=>update({time:e.target.value||undefined})}/></label><TimezoneSelect label="Routine timezone" value={draft.timezone} onChange={timezone=>update({timezone})}/><label>Routine location<input value={draft.location??''} maxLength={1000} onChange={e=>update({location:e.target.value})}/></label><label>Routine duration intent<input value={draft.durationIntent??''} maxLength={500} onChange={e=>update({durationIntent:e.target.value})}/></label><label>Routine duration (minutes)<input type="number" min="1" max="1440" value={draft.durationMinutes??''} onChange={e=>update({durationMinutes:e.target.value?Number(e.target.value):undefined})}/></label></div><label>Preferred time<input value={draft.preferredTime?.text??''} placeholder="Before lunch…" onChange={e=>update({preferredTime:e.target.value?{text:e.target.value}:undefined})}/></label>{draft.preferredTime?.status&&<p>{draft.preferredTime.status}: {draft.preferredTime.interpretation?.value}</p>}<p className="muted">Time preferences guide scheduling; they do not assign a time.</p><h3>Notes</h3><NotesEditor value={draft.notes} onChange={notes=>update({notes})}/>{error&&<p role="alert">{error} Your draft is preserved.</p>}</div><div className="resource-actions"><button className="save-button" disabled={saving}>Save routine</button><button type="button" className="archive-button" disabled={saving} onClick={()=>{if(draft.archived||window.confirm('Archive this routine? Past completions are kept.'))void save({...draft,archived:!draft.archived})}}>{draft.archived?'Restore':'Archive'} routine</button></div></form></Sheet>
}
