import {chromium} from 'playwright'
import assert from 'node:assert/strict'
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium-browser',headless:true,args:['--no-sandbox']})
async function selectZone(page,zone){await page.getByRole('combobox',{name:'Display timezone',exact:true}).click();await page.getByRole('combobox',{name:'Search display timezone',exact:true}).fill(zone);await page.getByRole('option').filter({has:page.getByText(zone,{exact:true})}).click()}
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3181'
try {
 const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.clock.install({time:new Date('2026-09-26T23:59:30Z')});await page.goto(base);await page.getByRole('button',{name:'Day Notes'}).click();const sheet=page.getByRole('dialog',{name:'Day Notes',exact:true});await sheet.getByRole('textbox',{name:'Period notes'}).fill('Before midnight draft');const captured=await sheet.locator('p.muted').innerText()
 await page.clock.runFor(31_000);assert.equal(await sheet.locator('p.muted').innerText(),captured);assert.match(await sheet.getByRole('textbox',{name:'Period notes'}).innerText(),/Before midnight draft/);await sheet.getByRole('button',{name:'Save notes'}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('button',{name:'Day Notes'}).click();assert.notEqual(await sheet.locator('p.muted').innerText(),captured);assert.equal((await sheet.getByRole('textbox',{name:'Period notes'}).innerText()).trim(),'');await page.keyboard.press('Escape')
 await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByRole('combobox',{name:'Display timezone',exact:true}).click();await page.getByRole('combobox',{name:'Search display timezone',exact:true}).fill('Not/A_Zone');await page.getByText('No matching timezone. Try a city or IANA name.').waitFor();await page.keyboard.press('Escape');await selectZone(page,'America/Los_Angeles');await page.getByLabel('Week starts on').selectOption('0');await page.getByLabel('Time format').selectOption('12-hour');await page.getByRole('button',{name:'Save preferences'}).click();await page.getByRole('status').waitFor();await page.getByRole('link',{name:'Week',exact:true}).click();assert.equal(await page.locator('.week-glance li').first().locator('span').first().innerText(),'Sun');await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:'Day Notes'}).click();assert.equal(await sheet.locator('p.muted').innerText(),captured);assert.match(await sheet.getByRole('textbox',{name:'Period notes'}).innerText(),/Before midnight draft/);await page.keyboard.press('Escape')
 await page.getByRole('link',{name:'Settings',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'Display timezone',exact:true}).getAttribute('data-timezone'),'America/Los_Angeles');assert.equal(await page.getByLabel('Week starts on').inputValue(),'0');assert.equal(await page.getByLabel('Time format').inputValue(),'12-hour');await page.getByRole('button',{name:'Reset floating-button positions'}).click();await page.getByRole('link',{name:'Today',exact:true}).click();const fab=await page.getByTestId('floating-add').boundingBox();assert.ok(fab.x>150&&fab.y>600);assert.match(await page.locator('.agenda-row .time').allTextContents().then(v=>v.join(' ')),/[ap]m/i);await page.getByRole('link',{name:'Settings',exact:true}).click()
 const other=await context.newPage();await other.goto(base+'/settings');assert.notEqual(await other.getByRole('combobox',{name:'Display timezone',exact:true}).getAttribute('data-timezone'),'America/Los_Angeles');assert.equal(await other.getByLabel('Week starts on').inputValue(),'1');await other.close()
 await page.reload();await page.getByLabel('Display timezone').waitFor();assert.notEqual(await page.getByRole('combobox',{name:'Display timezone',exact:true}).getAttribute('data-timezone'),'America/Los_Angeles');assert.equal(await page.getByLabel('Week starts on').inputValue(),'1');assert.equal(await page.getByLabel('Time format').inputValue(),'24-hour');assert.equal(await page.evaluate(()=>localStorage.length),0)
 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:'Day Notes'}).click();assert.equal((await sheet.getByRole('textbox',{name:'Period notes'}).innerText()).trim(),'');await page.keyboard.press('Escape');assert.deepEqual(errors,[])
 await context.close();assert.deepEqual(errors,[])
 // Independent clock origin: do not give one shared ServiceWorker two simulated dates.
 const weeklyContext=await browser.newContext({viewport:{width:390,height:844}});const weekly=await weeklyContext.newPage();weekly.on('pageerror',e=>errors.push(e.message));await weekly.clock.install({time:new Date('2026-09-27T23:59:30Z')});await weekly.goto(base+'/settings');await selectZone(weekly,'UTC');await weekly.getByRole('button',{name:'Save preferences'}).click();await weekly.getByRole('link',{name:'Week',exact:true}).click();await weekly.getByRole('button',{name:'View 2026-09-27',exact:true}).click();await weekly.getByRole('button',{name:'Day Notes',exact:false}).click();const capturedSheet=weekly.getByRole('dialog',{name:'Day Notes',exact:true});await capturedSheet.getByRole('textbox',{name:'Period notes'}).fill('Keep the selected-day draft through Monday');await weekly.clock.runFor(31_000);assert.equal(await capturedSheet.locator('p.muted').innerText(),'2026-09-27');assert.match(await capturedSheet.getByRole('textbox',{name:'Period notes'}).innerText(),/through Monday/);await capturedSheet.getByRole('button',{name:'Save notes'}).click();await capturedSheet.waitFor({state:'hidden'});const savedNotes=await weekly.evaluate(async()=>await(await fetch('/api/period-notes')).json());assert.equal(savedNotes[0].period.start,'2026-09-27');assert.equal(savedNotes[0].period.end,'2026-09-27');assert.deepEqual(errors,[]);await weeklyContext.close()
 console.log('PASS D: midnight rollover retains captured draft, timezone projection, Sunday week, invalid search rejection, navigation retention, independent tab and reload reset')
}finally{await browser.close()}
