import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium-browser',headless:true,args:['--no-sandbox']})
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3180'
await mkdir('artifacts',{recursive:true})
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true})
const page=await context.newPage()
const errors=[];page.on('pageerror',e=>errors.push(e.message))
try {
 await page.goto(base);await page.getByRole('button',{name:'Complete Choose herbs for the balcony'}).waitFor()
 const fab=page.getByTestId('floating-add');const original=await fab.boundingBox();assert.equal(await page.getByRole('button',{name:'Move add button'}).count(),0)
 assert.equal(await page.getByRole('navigation').count(),1)
 assert.equal(await page.locator('footer').count(),0)
 assert.equal(await fab.evaluate(e=>getComputedStyle(e).position),'fixed')
 const overflow=()=>page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)
 assert.equal(await overflow(),false)
 // Compact cards may fit without scrolling; provide a tall content fixture for overlay/scroll assertions.
 await page.locator('main').evaluate(e=>{e.style.minHeight='1600px'});await page.screenshot({path:'artifacts/phase2-today-mobile.png',fullPage:false});await page.evaluate(()=>window.scrollTo(0,180));let rect=await fab.boundingBox();assert.equal(rect.y,original.y)
 // Overlay must cover actual content, not occupy a reserved layout row.
 assert.ok(await fab.evaluate(e=>{const r=e.getBoundingClientRect();return document.elementsFromPoint(r.x+40,r.y+25).some(x=>x.closest('main'))}))
 await page.screenshot({path:'artifacts/phase2-today-mobile-scrolled.png',fullPage:false})
 await page.locator('.floating-primary').focus();await page.locator('.floating-primary').press('ArrowUp')
 await page.getByRole('button',{name:'top left',exact:true}).focus();await page.keyboard.press('Enter')
 const keyboardRect=await fab.boundingBox();assert.ok(keyboardRect.x<20&&keyboardRect.y>=72)
 await page.locator('.floating-primary').focus();await page.locator('.floating-primary').press('ArrowUp');assert.ok(await page.locator('.floating-placement').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}))
 await page.getByRole('button',{name:'bottom right',exact:true}).click()
 const button=page.getByRole('button',{name:'Add task',exact:true});const b=await button.boundingBox()
 await page.mouse.move(b.x+70,b.y+25);await page.mouse.down();await page.mouse.move(55,220,{steps:10});await page.mouse.up()
 const moved=await fab.boundingBox();assert.ok(moved.y<300);assert.ok(moved.x>=12)
 assert.equal(await page.locator('dialog[open]').count(),0)
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('heading',{name:'This week',exact:true}).waitFor()
 assert.equal(await page.locator('nav a[aria-current=page]').count(),1);assert.equal(await page.locator('nav a[aria-current=page]').textContent(),'Week');const retained=await fab.boundingBox();assert.equal(retained.x,moved.x);assert.equal(retained.y,moved.y)
 await page.setViewportSize({width:320,height:620});await page.waitForTimeout(100)
 const resized=await fab.boundingBox();assert.ok(resized.x>=0&&resized.x+resized.width<=320);assert.ok(resized.y>=0&&resized.y+resized.height<=620)
 assert.equal(await overflow(),false)
 await page.reload();await page.getByRole('button',{name:'Complete Choose herbs for the balcony'}).waitFor()
 assert.equal(await page.locator('nav a[aria-current=page]').textContent(),'Week');const reset=await fab.boundingBox();assert.ok(reset.y>resized.y)
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/phase2-week-mobile.png',fullPage:false})
 const glance=await page.getByRole('heading',{name:'Week at a glance'}).boundingBox();const priorities=await page.getByRole('heading',{name:'Priorities'}).boundingBox();assert.ok(glance.y<priorities.y)
 await page.getByRole('button',{name:'Week Notes'}).click();await page.getByRole('dialog',{name:'Week Notes'}).waitFor();await page.keyboard.press('Escape')
 await page.getByRole('link',{name:'Settings',exact:true}).click();assert.equal(await fab.isVisible(),false)
 await page.getByRole('link',{name:'Today',exact:true}).click();assert.equal(await fab.isVisible(),true)
 await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>window.scrollTo(0,0));assert.equal(await overflow(),false)
 await page.screenshot({path:'artifacts/phase2-today-desktop.png',fullPage:false})
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.waitForTimeout(200);await page.screenshot({path:'artifacts/phase2-week-desktop.png',fullPage:false})
 // UI corrections: one shared journey for target lifecycle, flip, and modal shell.
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.waitForTimeout(300)
 const correctionMain=page.locator('.floating-primary')
 const correctionTarget=page.getByRole('button',{name:'Move add button'})
 const dragCorrection=async(x,y)=>{const r=await correctionMain.boundingBox();await page.mouse.move(r.x+40,r.y+25);await page.mouse.down();await page.mouse.move(x+40,y+25,{steps:8});await page.mouse.up()}
 assert.equal(await correctionTarget.count(),0)
 await dragCorrection(12,12)
 assert.ok((await correctionTarget.getAttribute('data-placement')).startsWith('bottom'))
 await page.waitForTimeout(250);assert.ok(await correctionTarget.isVisible())
 await dragCorrection(20,30);await page.waitForTimeout(300);assert.ok(await correctionTarget.isVisible())
 await correctionTarget.click();await page.waitForTimeout(750)
 assert.ok(await page.getByRole('group',{name:'Add button position'}).isVisible())
 await page.getByRole('button',{name:'bottom right',exact:true}).click()
 await correctionMain.press('Escape')
 await dragCorrection(20,760)
 assert.ok((await correctionTarget.getAttribute('data-placement')).startsWith('top'))
 await page.waitForTimeout(540);assert.ok((await correctionTarget.getAttribute('class')).includes('is-fading'))
 await page.waitForTimeout(160);assert.equal(await correctionTarget.count(),0)
 await correctionMain.click()
 const correctionDialog=page.locator('dialog[open]')
 assert.equal(await correctionDialog.count(),1)
 await correctionDialog.locator('.resource-top').click();assert.equal(await correctionDialog.count(),1)
 const headerBefore=await correctionDialog.locator('.resource-top').boundingBox()
 const footerBefore=await correctionDialog.locator('.resource-actions').boundingBox()
 await correctionDialog.locator('.resource-body').evaluate(el=>{el.scrollTop=el.scrollHeight})
 const headerAfter=await correctionDialog.locator('.resource-top').boundingBox()
 const footerAfter=await correctionDialog.locator('.resource-actions').boundingBox()
 assert.equal(headerBefore.y,headerAfter.y);assert.equal(footerBefore.y,footerAfter.y)
 assert.ok(footerAfter.y+footerAfter.height<=844)
 await page.mouse.click(2,2);assert.equal(await correctionDialog.count(),0)
 assert.equal(await correctionMain.evaluate(el=>el===document.activeElement),true)
 await correctionMain.click();await correctionDialog.getByRole('textbox',{name:'Task name',exact:true}).fill('Keep this draft')
 const contentRect=await correctionDialog.locator('.resource-top').boundingBox()
 await page.mouse.move(contentRect.x+20,contentRect.y+10);await page.mouse.down();await page.mouse.move(2,2);await page.mouse.up()
 assert.equal(await correctionDialog.count(),1)
 page.once('dialog',d=>d.dismiss());await page.mouse.click(2,2)
 assert.equal(await correctionDialog.getByRole('textbox',{name:'Task name',exact:true}).inputValue(),'Keep this draft')
 await page.setViewportSize({width:320,height:620})
 const narrowBody=await correctionDialog.locator('.resource-body').evaluate(el=>({height:el.clientHeight,scroll:el.scrollHeight}))
 assert.ok(narrowBody.scroll>narrowBody.height)
 const narrowFooter=await correctionDialog.locator('.resource-actions').boundingBox();assert.ok(narrowFooter.y+narrowFooter.height<=620)
 await page.screenshot({path:'artifacts/ui-corrections-modal-mobile.png'})
 page.once('dialog',d=>d.accept());await page.mouse.click(2,2);assert.equal(await correctionDialog.count(),0)

 assert.equal(await page.locator('.demo').count(),0)
 assert.deepEqual(errors,[])
 console.log('Browser E passed: phone/desktop shell, single nav, overlay, fixed scroll, drag, keyboard placement, route retention, resize bounds, reload reset, honest Notes dialog.')
} finally {await browser.close()}
