import {chromium} from 'playwright'
import assert from 'node:assert/strict'
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium-browser',headless:true,args:['--no-sandbox']})
try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.PREVIEW_URL||'http://127.0.0.1:3181';
 await page.goto(base+'/settings');await page.getByRole('button',{name:'New project'}).click();const sheet=page.locator('dialog[open]');
 await sheet.getByRole('textbox',{name:'Project name'}).fill('Weekend studio');await sheet.getByLabel('Target date (optional)').fill('2026-10-03');
 await sheet.locator('.ProseMirror').fill('A calm place to make things.');await sheet.getByRole('button',{name:'Create project',exact:true}).click();await sheet.waitFor({state:'hidden'});
 await page.getByRole('button',{name:/Weekend studio/}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),/A calm place/);await sheet.getByRole('button',{name:'Add task',exact:true}).click();
 await sheet.getByRole('textbox',{name:'Task name'}).fill('Choose a desk lamp');await sheet.getByLabel('Scheduled date',{exact:true}).fill(await page.evaluate(()=>new Intl.DateTimeFormat('en-CA',{timeZone:window.MEOS_CONFIG.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())));await sheet.getByLabel('Time (required when scheduled)',{exact:true}).fill('10:30');await sheet.getByLabel('Duration (minutes)',{exact:true}).fill('30');
 await sheet.locator('.ProseMirror').fill('Warm light, easy to adjust.');await sheet.getByRole('button',{name:'+ Add reference',exact:true}).click();await sheet.getByLabel('Reference 1 label').fill('Inspiration');await sheet.getByLabel('Reference 1 URL').fill('https://example.com/lamp');
 await sheet.getByRole('button',{name:'Create task',exact:true}).click();await sheet.waitFor({state:'hidden'});
 await page.getByRole('button',{name:/Weekend studio/}).click();await sheet.getByRole('button',{name:'Choose a desk lamp',exact:true}).click();assert.equal(await sheet.getByLabel('Reference 1 URL').inputValue(),'https://example.com/lamp');assert.match(await sheet.locator('.ProseMirror').innerText(),/Warm light/);assert.equal(await sheet.getByLabel('Time (required when scheduled)',{exact:true}).inputValue(),'10:30');
 await sheet.locator('summary').click();await page.screenshot({path:'artifacts/phase3-task-mobile.png'});await sheet.getByRole('textbox',{name:'Task name'}).fill('Choose an adjustable lamp');await sheet.locator('.ProseMirror').fill('Warm light, with a sturdy base.');
 // Invalid reference fails the real mock service; a corrected retry retains all drafts.
 await sheet.getByLabel('Reference 1 URL').fill('ftp://example.com/lamp');await sheet.getByRole('button',{name:'Save changes',exact:true}).click();await sheet.getByRole('alert').waitFor();assert.equal(await sheet.getByRole('textbox',{name:'Task name'}).inputValue(),'Choose an adjustable lamp');assert.match(await sheet.locator('.ProseMirror').innerText(),/sturdy base/);
 await sheet.getByLabel('Reference 1 URL').fill('https://example.com/lamp');await sheet.getByRole('button',{name:'Save changes',exact:true}).click();await sheet.waitFor({state:'hidden'});
 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:'Complete Choose an adjustable lamp',exact:true}).click();await page.getByRole('link',{name:'Week',exact:true}).click();const today=await page.evaluate(()=>new Intl.DateTimeFormat('en-CA',{timeZone:window.MEOS_CONFIG.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()));await page.getByRole('button',{name:`View ${today}`,exact:true}).click();await page.locator('details.completed-tasks summary').click();await page.getByRole('button',{name:'Reopen Choose an adjustable lamp',exact:true}).waitFor();
 await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:/Weekend studio/}).click();await sheet.locator('summary').click();await page.screenshot({path:'artifacts/phase3-project-mobile.png'});await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'artifacts/phase3-project-desktop.png'});
 page.once('dialog',d=>d.accept());await sheet.getByRole('button',{name:'Archive project',exact:true}).click();await sheet.waitFor({state:'hidden'});
 const orphan=page.locator('section').filter({has:page.getByRole('heading',{name:'No project',exact:true})});await orphan.getByRole('button',{name:'Choose an adjustable lamp',exact:true}).waitFor();await orphan.getByRole('button',{name:'Find a frame for the hallway',exact:true}).waitFor();
 await page.getByText('Archived resources',{exact:true}).click();await page.getByRole('button',{name:'Weekend studio',exact:true}).click();await sheet.getByRole('button',{name:'Restore project',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('button',{name:/○ Weekend studio/}).click();await sheet.getByRole('textbox',{name:'Project name'}).fill('Unsaved change');page.once('dialog',d=>d.dismiss());await sheet.getByRole('button',{name:'Close details',exact:true}).click();assert.equal(await sheet.getByRole('textbox',{name:'Project name'}).inputValue(),'Unsaved change');page.once('dialog',d=>d.accept());await sheet.getByRole('button',{name:'Close details',exact:true}).click();await sheet.waitFor({state:'hidden'});
 if(errors.length)throw Error(errors.join('\n'));console.log('PASS B: project/task create, ProseMirror notes/reference save/reopen, scheduling, cross-view completion, rejected save retains draft, archive unassigns, unscheduled orphan discovery')
}finally{await browser.close()}
