import {chromium} from 'playwright'
import assert from 'node:assert/strict'
import {mkdir} from 'node:fs/promises'
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium-browser',headless:true,args:['--no-sandbox']})
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3181'
try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByRole('button',{name:'Complete Choose herbs for the balcony',exact:true}).waitFor()
 const today=await page.evaluate(()=>new Intl.DateTimeFormat('en-CA',{timeZone:window.MEOS_CONFIG.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()))
 const tomorrow=new Date(today+'T12:00:00Z');tomorrow.setUTCDate(tomorrow.getUTCDate()+1);const tomorrowDate=tomorrow.toISOString().slice(0,10)
 await page.getByRole('button',{name:'Choose herbs for the balcony',exact:true}).click();const taskSheet=page.getByRole('dialog',{name:'Edit task',exact:true});await taskSheet.getByLabel('Scheduled date',{exact:true}).fill(tomorrowDate);await taskSheet.getByRole('button',{name:'Save changes',exact:true}).click();await taskSheet.waitFor({state:'hidden'});await page.getByRole('button',{name:'Complete Choose herbs for the balcony',exact:true}).waitFor({state:'hidden'})
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('button',{name:'Complete Choose herbs for the balcony',exact:true}).waitFor()
 if(!await page.getByRole('button',{name:`View ${tomorrowDate}`,exact:true}).count())await page.getByRole('button',{name:'Next week',exact:true}).click()
 await page.getByRole('button',{name:`View ${tomorrowDate}`,exact:true}).click();await page.getByRole('region',{name:'Scheduled agenda'}).getByRole('button',{name:'Complete Choose herbs for the balcony',exact:true}).waitFor()
 // Weekly association removal leaves original task and its priority untouched.
 await page.getByRole('button',{name:'This week',exact:true}).click();await page.getByRole('button',{name:'Remove Choose herbs for the balcony from week',exact:true}).click();await page.getByRole('button',{name:'Remove Choose herbs for the balcony from week',exact:true}).waitFor({state:'hidden'})
 await page.getByRole('button',{name:'Next week',exact:true}).click();await page.getByRole('button',{name:'Add outcome',exact:true}).click();let sheet=page.getByRole('dialog',{name:'Add outcome',exact:true});await sheet.getByLabel('Choose an existing task').selectOption({label:'Choose herbs for the balcony'});await sheet.getByRole('button',{name:'Add to week'}).click();await sheet.waitFor({state:'hidden'})
 await page.getByRole('button',{name:'Remove Choose herbs for the balcony from week',exact:true}).waitFor();await page.getByRole('button',{name:'Add outcome',exact:true}).click();await sheet.getByLabel('New outcome name').fill('Make space for a book');await page.evaluate(()=>{const original=window.fetch;let fail=true;window.fetch=(input,init)=>{if(fail&&String(input).includes('/outcomes/')&&init?.method==='PUT'){fail=false;return Promise.resolve(new Response(JSON.stringify({error:'Simulated membership failure'}),{status:503,headers:{'Content-Type':'application/json'}}))}return original(input,init)}});await sheet.getByRole('button',{name:'Add to week'}).click();await sheet.getByRole('alert').waitFor();assert.equal(await sheet.getByLabel('New outcome name').inputValue(),'Make space for a book');assert.equal(await sheet.getByLabel('Choose an existing task').isDisabled(),true);await sheet.getByRole('button',{name:'Add to week'}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('button',{name:'Make space for a book',exact:true}).waitFor()
 await page.getByRole('button',{name:'This week',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Make space for a book',exact:true}).count(),0)
 const state=await page.evaluate(async()=>({tasks:await(await fetch('/api/tasks')).json(),outcomes:await(await fetch('/api/outcomes')).json()}));assert.equal(state.tasks.filter(t=>t.title==='Choose herbs for the balcony').length,1);assert.equal(state.tasks.find(t=>t.title==='Choose herbs for the balcony').priority,'high');assert.equal(state.tasks.find(t=>t.title==='Make space for a book').priority,'none');assert.equal(state.tasks.filter(t=>t.title==='Make space for a book').length,1)
 // One occurrence completion never marks adjacent day or definition complete.
 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:`Complete Morning care on ${today}`,exact:true}).click();await page.getByRole('button',{name:`Reopen Morning care on ${today}`,exact:true}).waitFor();await page.getByRole('link',{name:'Week',exact:true}).click();if(!await page.getByRole('button',{name:`View ${tomorrowDate}`,exact:true}).count())await page.getByRole('button',{name:'Next week',exact:true}).click();await page.getByRole('button',{name:`View ${tomorrowDate}`,exact:true}).click();await page.getByRole('button',{name:`Complete Morning care on ${tomorrowDate}`,exact:true}).waitFor()
 await page.getByRole('button',{name:'New routine',exact:true}).click();sheet=page.getByRole('dialog',{name:'Routine details'});await sheet.getByLabel('Routine name').fill('Stretch gently');await sheet.getByLabel('Frequency intent',{exact:true}).fill('Every day');await sheet.getByLabel('Routine duration intent',{exact:true}).fill('About fifteen minutes');await sheet.getByRole('combobox',{name:'Routine timezone',exact:true}).click();await sheet.getByRole('combobox',{name:'Search routine timezone',exact:true}).fill('invalid/zone');await sheet.getByText('No matching timezone. Try a city or IANA name.').waitFor();assert.equal(await sheet.getByLabel('Routine name').inputValue(),'Stretch gently');await page.keyboard.press('Escape');await sheet.getByRole('button',{name:'Save routine'}).click();await sheet.waitFor({state:'hidden'})
 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:`Complete Stretch gently on ${today}`,exact:true}).waitFor()
 // Save/reopen and dirty dismissal retain rich period note content.
 await page.getByRole('button',{name:'Day Notes'}).click();sheet=page.getByRole('dialog',{name:'Day Notes',exact:true});await sheet.getByRole('textbox',{name:'Period notes'}).fill('A little room for today.');await sheet.getByRole('button',{name:'Close planner details'}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('button',{name:'Day Notes'}).click();assert.match(await sheet.getByRole('textbox',{name:'Period notes'}).innerText(),/little room/);await sheet.getByRole('textbox',{name:'Period notes'}).fill('Keep my note');await sheet.getByRole('button',{name:'Close planner details'}).click();await sheet.waitFor({state:'hidden'})
 // Week notes are separate by selected period; routine archive/restore keeps history.
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('button',{name:'This week',exact:true}).click();await page.getByRole('button',{name:'Week Notes'}).click();sheet=page.getByRole('dialog',{name:'Week Notes',exact:true});await sheet.getByRole('textbox',{name:'Period notes'}).fill('This week has room.');await sheet.getByRole('button',{name:'Close planner details'}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('button',{name:'Next week',exact:true}).click();await page.getByRole('button',{name:'Week Notes'}).click();assert.equal((await sheet.getByRole('textbox',{name:'Period notes'}).innerText()).trim(),'');await page.keyboard.press('Escape');await page.getByRole('button',{name:/^Morning care/}).click();sheet=page.getByRole('dialog',{name:'Routine details'});await Promise.all([page.waitForEvent('dialog').then(d=>d.accept()),sheet.getByRole('button',{name:'Archive routine',exact:true}).click()]);await sheet.waitFor({state:'hidden'});await page.getByText('Archived routines',{exact:true}).click();await page.getByRole('button',{name:'Morning care',exact:true}).click();await sheet.getByRole('button',{name:'Restore routine',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:`Reopen Morning care on ${today}`,exact:true}).waitFor()
 await mkdir('artifacts',{recursive:true});await page.screenshot({path:'artifacts/phase4-today-mobile.png',fullPage:true});await page.getByRole('link',{name:'Week',exact:true}).click();await page.screenshot({path:'artifacts/phase4-week-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'artifacts/phase4-week-desktop.png',fullPage:true})
 assert.deepEqual(errors,[]);console.log('PASS C: defer/projected agenda, independent weekly outcomes, no duplicate task, routine recurrence/completion, period notes and dirty-close protection')
}finally{await browser.close()}
