import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
const browser=await chromium.launch({executablePath:'/usr/bin/chromium-browser',headless:true,args:['--no-sandbox']})
const base=process.env.PREVIEW_URL||'http://127.0.0.1:3180'
await mkdir('artifacts',{recursive:true})
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true})
const page=await context.newPage()
const errors=[];page.on('pageerror',e=>errors.push(e.message))
try {
 await page.goto(base);await page.getByRole('button',{name:'Complete Choose herbs for the balcony'}).waitFor()
 const fab=page.getByTestId('floating-add');const original=await fab.boundingBox()
 assert.equal(await page.getByRole('navigation').count(),1)
 assert.equal(await page.locator('footer').count(),0)
 assert.equal(await fab.evaluate(e=>getComputedStyle(e).position),'fixed')
 const overflow=()=>page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)
 assert.equal(await overflow(),false)
 await page.screenshot({path:'artifacts/phase2-today-mobile.png',fullPage:false});await page.evaluate(()=>window.scrollTo(0,180));let rect=await fab.boundingBox();assert.equal(rect.y,original.y)
 // Overlay must cover actual content, not occupy a reserved layout row.
 assert.ok(await fab.evaluate(e=>{const r=e.getBoundingClientRect();return document.elementsFromPoint(r.x+40,r.y+25).some(x=>x.closest('main'))}))
 await page.screenshot({path:'artifacts/phase2-today-mobile-scrolled.png',fullPage:false})
 await page.getByRole('button',{name:'Move add button'}).click()
 await page.getByRole('button',{name:'top left',exact:true}).focus();await page.keyboard.press('Enter')
 const keyboardRect=await fab.boundingBox();assert.ok(keyboardRect.x<20&&keyboardRect.y>=72)
 await page.getByRole('button',{name:'Move add button'}).click();assert.ok(await page.locator('#placement-menu').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}))
 await page.getByRole('button',{name:'bottom right',exact:true}).click()
 const button=page.getByRole('button',{name:'Add task',exact:true});const b=await button.boundingBox()
 await page.mouse.move(b.x+70,b.y+25);await page.mouse.down();await page.mouse.move(55,220,{steps:10});await page.mouse.up()
 const moved=await fab.boundingBox();assert.ok(moved.y<300);assert.ok(moved.x>=12)
 assert.equal(await page.getByRole('dialog').count(),0)
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('heading',{name:'This week',exact:true}).waitFor()
 assert.equal(await page.locator('nav a[aria-current=page]').count(),1);assert.equal(await page.locator('nav a[aria-current=page]').textContent(),'Week');const retained=await fab.boundingBox();assert.equal(retained.x,moved.x);assert.equal(retained.y,moved.y)
 await page.setViewportSize({width:320,height:620});await page.waitForTimeout(100)
 const resized=await fab.boundingBox();assert.ok(resized.x>=0&&resized.x+resized.width<=320);assert.ok(resized.y>=0&&resized.y+resized.height<=620)
 assert.equal(await overflow(),false)
 await page.reload();await page.getByRole('button',{name:'Complete Choose herbs for the balcony'}).waitFor()
 assert.equal(await page.locator('nav a[aria-current=page]').textContent(),'Week');const reset=await fab.boundingBox();assert.ok(reset.y>resized.y)
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/phase2-week-mobile.png',fullPage:false})
 const glance=await page.getByRole('heading',{name:'Week at a glance'}).boundingBox();const priorities=await page.getByRole('heading',{name:'Priorities'}).boundingBox();assert.ok(glance.y<priorities.y)
 await page.getByRole('button',{name:'Week Notes'}).click();await page.getByRole('dialog',{name:'Week Notes'}).waitFor();await page.keyboard.press('Escape')
 await page.getByRole('link',{name:'Settings',exact:true}).click();assert.equal(await fab.isVisible(),false)
 await page.getByRole('link',{name:'Today',exact:true}).click();assert.equal(await fab.isVisible(),true)
 await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>window.scrollTo(0,0));assert.equal(await overflow(),false)
 await page.screenshot({path:'artifacts/phase2-today-desktop.png',fullPage:false})
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.waitForTimeout(200);await page.screenshot({path:'artifacts/phase2-week-desktop.png',fullPage:false})
 assert.deepEqual(errors,[])
 console.log('Browser E passed: phone/desktop shell, single nav, overlay, fixed scroll, drag, keyboard placement, route retention, resize bounds, reload reset, honest Notes dialog.')
} finally {await browser.close()}
