// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import fs from 'node:fs'
import https from 'node:https'
import http from 'node:http'
import path from 'node:path'
import {createHash} from 'node:crypto'
import {spawnSync} from 'node:child_process'
import {chromium} from 'playwright'
import {createNodeWebHandler,unixUpstream} from '../backend/node-web-server.mjs'
const origin=JSON.parse(fs.readFileSync('private/acceptance-endpoint.json')).origin,checks=[],errors=[];let dropComplete=false,dropTask=false,dropOutcome=false,projectWrites=0;const completionKeys=[],taskKeys=[],outcomeIds=[],operationStatuses=[]
const credentials=JSON.parse(fs.readFileSync('private/synthetic-credentials.json'))
const tls=spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout','/tmp/meos-key.pem','-out','/tmp/meos-cert.pem','-days','1','-subj','/CN='+new URL(origin).hostname],{stdio:'ignore'});assert.equal(tls.status,0)
const upstream=unixUpstream({origin,socketPath:'/run/meos-acceptance-data/server.sock'})
const handler=createNodeWebHandler({origin,root:'dist/client',upstream:async request=>{
 const body=request.method==='GET'?null:await request.clone().json().catch(()=>null),url=new URL(request.url)
 const response=await upstream(request)
 if(url.pathname.includes('/operations/'))operationStatuses.push([url.pathname,response.status,body?.routineId??null])
 if(url.pathname==='/api/meos/v1/resources/projects'&&request.method==='POST')projectWrites++
 if(url.pathname==='/api/meos/v1/operations/create_task'){taskKeys.push(body.value.id);if(dropTask&&response.ok){dropTask=false;return new Response('{}',{status:503})}}
 if(url.pathname==='/api/meos/v1/resources/outcomes'&&request.method==='POST'){outcomeIds.push(body.value.id);if(dropOutcome&&response.ok){dropOutcome=false;return new Response('{}',{status:503})}}
 if(url.pathname==='/api/meos/v1/operations/complete_occurrence'){completionKeys.push(body.idempotencyKey);if(dropComplete&&response.ok){dropComplete=false;return new Response('{}',{status:503})}}
 return response
}})
// Only this qualification wrapper serves the legacy worker fixture. Production does not.
const server=https.createServer({key:fs.readFileSync('/tmp/meos-key.pem'),cert:fs.readFileSync('/tmp/meos-cert.pem')},(req,res)=>{if(req.url==='/mockServiceWorker.js'){res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync('dist/client/mockServiceWorker.js'));return}void handler(req,res)})
await new Promise(resolve=>server.listen(8443,'127.0.0.1',resolve))
const publicKey=spawnSync('openssl',['x509','-in','/tmp/meos-cert.pem','-pubkey','-noout']).stdout;const spki=createHash('sha256').update(spawnSync('openssl',['pkey','-pubin','-outform','der'],{input:publicKey}).stdout).digest('base64')
const browser=await chromium.launch({executablePath:'/opt/playwright/browsers/chromium-1208/chrome-linux64/chrome',headless:true,args:['--no-sandbox','--ignore-certificate-errors-spki-list='+spki,'--no-proxy-server','--host-resolver-rules=MAP '+new URL(origin).hostname+' 127.0.0.1:8443']})
const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1280,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.setDefaultTimeout(12000)
async function login(user){await page.goto(origin+'/settings');await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill(user.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Settings',exact:true}).waitFor()}
const suffix=Date.now().toString(36),project='Project '+suffix,task='Task '+suffix
try{
 if(process.argv[2]==='restart'){const fixture=JSON.parse(fs.readFileSync('private/persistence-fixture.json'));await login(credentials.users[0]);await page.getByText('Archived resources',{exact:true}).click();await page.getByRole('button',{name:fixture.project,exact:true}).click();const sheet=page.locator('dialog[open]');assert.match(await sheet.locator('.ProseMirror').innerText(),/Persistent project notes/);await sheet.getByRole('button',{name:'Close details',exact:true}).click();await page.getByRole('button',{name:fixture.task,exact:true}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),/Persistent task notes/);await sheet.getByRole('button',{name:'Close details',exact:true}).click();await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('heading',{name:'Week at a glance',exact:true}).waitFor();await page.getByRole('button',{name:'This week',exact:true}).click();await page.getByRole('heading',{name:'This week',exact:true}).waitFor();if(!await page.getByRole('button',{name:`View ${fixture.tomorrow}`,exact:true}).count())await page.getByRole('button',{name:'Next week',exact:true}).click();await page.getByRole('button',{name:`View ${fixture.tomorrow}`,exact:true}).click();await page.getByRole('button',{name:`Edit instance ${fixture.routine}`,exact:true}).waitFor();fs.writeFileSync('persistence-evidence.json',JSON.stringify({runId:process.env.MEOS_ACCEPTANCE_RUN,checks:['ordinary cookie login after controlled backend restart','archived project notes preserved','task edits and notes preserved','moved instance visible on scheduled date'],count:4},null,2));console.log('PASS 4 browser restart persistence checks')}else{
 await page.goto(origin+'/settings');await page.getByRole('heading',{name:'Sign in to MeOS'}).waitFor();await page.evaluate(async()=>{await navigator.serviceWorker.register('/mockServiceWorker.js');await navigator.serviceWorker.ready});await page.reload();await page.getByRole('heading',{name:'Sign in to MeOS'}).waitFor();assert.equal(await page.evaluate(async()=>(await navigator.serviceWorker.getRegistrations()).length),0);checks.push('real mode unregisters legacy demo service worker before authenticated data loads');
 await login(credentials.users[0]);checks.push('real browser cookie login and authenticated Settings')
 await page.getByRole('button',{name:'New project',exact:true}).click();const sheet=page.locator('dialog[open]');await sheet.getByLabel('Project name',{exact:true}).fill(project);await sheet.locator('.ProseMirror').fill('Persistent project notes');await sheet.getByRole('button',{name:'Create project',exact:true}).click();await sheet.waitFor({state:'hidden'});checks.push('project and ProseMirror save')
 await page.getByRole('button',{name:new RegExp(project)}).click();await sheet.getByRole('button',{name:'Add task',exact:true}).click();await sheet.getByLabel('Task name',{exact:true}).fill(task);await sheet.getByLabel('Scheduled date',{exact:true}).fill(new Date().toISOString().slice(0,10));await sheet.getByLabel('Time (required when scheduled)',{exact:true}).fill('12:30');await sheet.getByLabel(/^Preferred time/).fill('before lunch');await sheet.locator('.ProseMirror').fill('Persistent task notes');await sheet.getByRole('button',{name:'Create task',exact:true}).click();await sheet.waitFor({state:'hidden'});checks.push('generated create_task operation through existing editor')
 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:'Complete '+task,exact:true}).click();await page.reload();await page.getByRole('button',{name:'Reopen '+task,exact:true}).waitFor();checks.push('Today completion persists across reload')
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('heading',{name:/Week/}).first().waitFor();checks.push('real Week renders')
 await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:new RegExp(project)}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),/Persistent project notes/);await sheet.getByRole('button',{name:task,exact:true}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),/Persistent task notes/);assert.equal(await sheet.getByLabel(/^Preferred time/).inputValue(),'before lunch');await sheet.getByRole('button',{name:'Close details',exact:true}).click();checks.push('project/task notes and preference round trip')

 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const session=await(await fetch('/api/meos/v1/session')).json();const result=await fetch('/api/meos/v1'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:body===undefined?undefined:JSON.stringify(body)});return {status:result.status,body:await result.json().catch(()=>null)}},{path,method,body})
 const weatherPrefs=(await api('/preferences')).body;assert.equal((await api('/preferences','PUT',{value:{...weatherPrefs.value,weather:{enabled:false,source:'latest',units:'celsius'}},expectedRevision:weatherPrefs.revision})).status,200);await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByText('Weather is disabled',{exact:true}).waitFor();const disabledPrefs=(await api('/preferences')).body;assert.equal((await api('/preferences','PUT',{value:{...disabledPrefs.value,weather:{enabled:true,source:'latest',units:'celsius'}},expectedRevision:disabledPrefs.revision})).status,200);await page.reload();await page.getByText(/Weather unavailable/).waitFor();const fallbackPrefs=(await api('/preferences')).body;await api('/preferences','PUT',{value:{...fallbackPrefs.value,weather:{enabled:false,source:'latest',units:'celsius'}},expectedRevision:fallbackPrefs.revision});checks.push('weather disabled and unavailable screens leave planning usable without live provider effects');await page.getByRole('link',{name:'Settings',exact:true}).click();
 await page.getByRole('button',{name:'New task',exact:true}).click();await sheet.getByLabel('Task name',{exact:true}).fill('DST fold '+suffix);await sheet.getByLabel('Scheduled date',{exact:true}).fill('2026-11-01');await sheet.getByLabel('Time (required when scheduled)',{exact:true}).fill('01:30');await sheet.locator('.timezone-trigger').click();await sheet.getByLabel('Search timezone',{exact:true}).fill('America/New_York');await sheet.getByRole('option').filter({hasText:'America/New_York'}).click();await sheet.getByRole('button',{name:'Create task',exact:true}).click();await sheet.getByRole('alert').waitFor();assert.equal(await sheet.getByLabel('Task name',{exact:true}).inputValue(),'DST fold '+suffix);await sheet.getByLabel('UTC offset in minutes (required for repeated DST times)',{exact:true}).fill('-240');await sheet.getByRole('button',{name:'Create task',exact:true}).click();await sheet.waitFor({state:'hidden'});const dstTask=(await api('/resources/tasks')).body.items.find(r=>r.value.title==='DST fold '+suffix);assert.equal(dstTask.value.schedule.offsetMinutes,-240);checks.push('DST fold rejects ambiguous clock while preserving draft, then saves explicit offset through timezone picker');
 const allRows=async(kind)=>{const items=[];let cursor;do{const result=await api('/resources/'+kind+'?limit=250'+(cursor?'&cursor='+cursor:''));assert.equal(result.status,200);items.push(...result.body.items);cursor=result.body.nextCursor}while(cursor);return items}
 const routine='Routine '+suffix
 await page.getByRole('button',{name:'New routine',exact:true}).click();await sheet.getByLabel('Routine name',{exact:true}).fill(routine);await sheet.getByLabel('Frequency intent',{exact:true}).fill('every day');await sheet.getByLabel('Routine duration intent',{exact:true}).fill('About 30 minutes');await sheet.getByLabel('Preferred time',{exact:true}).fill('in the morning');await sheet.getByRole('button',{name:'Save routine',exact:true}).click();await sheet.waitFor({state:'hidden'});
 const routineRow=(await api('/resources/routines')).body.items.find(r=>r.value.title===routine)
 const today=new Date().toISOString().slice(0,10),dates=Array.from({length:15},(_,i)=>new Date(Date.parse(today+'T00:00Z')+i*86400000).toISOString().slice(0,10));assert.equal((await allRows('occurrences')).filter(r=>r.value.routineId===routineRow.value.id).length,0,'template save does not create instances');
 const planned=await api('/operations/plan_routines','POST',{routines:[{routineId:routineRow.value.id,expectedRevision:routineRow.revision,period:{start:today,end:dates.at(-1)},ids:Object.fromEntries(dates.map(date=>[date,crypto.randomUUID()]))}],idempotencyKey:crypto.randomUUID()});assert.equal(planned.status,200);
 const all=(await allRows('occurrences')).filter(r=>r.value.routineId===routineRow.value.id);assert.equal(all.length,15);assert(all.every(r=>!r.value.schedule&&r.value.durationMinutes===undefined));const instance=all.find(r=>r.value.date===today);assert(instance);checks.push('intent template creates no instances; explicit planning creates unscheduled bounded snapshots');
 assert.equal((await api('/operations/move_occurrence','POST',{id:instance.value.id,expectedRevision:instance.revision,idempotencyKey:crypto.randomUUID(),schedule:{date:today,time:'11:15',timezone:'UTC'},durationMinutes:30})).status,200);await page.reload();
 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:`Complete ${routine} on ${today}`,exact:true}).waitFor();dropComplete=true;await page.getByRole('button',{name:`Complete ${routine} on ${today}`,exact:true}).click();await page.getByRole('alert').filter({hasText:/503|Service could not/}).waitFor();await page.getByRole('button',{name:`Complete ${routine} on ${today}`,exact:true}).click();await page.getByRole('button',{name:`Reopen ${routine} on ${today}`,exact:true}).waitFor();assert.equal(completionKeys.at(-1),completionKeys.at(-2));checks.push('uncertain committed occurrence completion retries same idempotency key')
 await page.getByRole('button',{name:`Edit instance ${routine}`,exact:true}).click();await sheet.getByLabel('Instance duration',{exact:true}).fill('');await sheet.getByRole('button',{name:'Save instance',exact:true}).click();assert.equal(await sheet.getByLabel('Instance duration',{exact:true}).evaluate(el=>el.validity.valueMissing),true);await sheet.getByLabel('Instance duration',{exact:true}).fill('45');checks.push('existing instance duration cannot silently clear; explicit replacement accepted');await sheet.getByLabel('Instance name',{exact:true}).fill(routine+' moved');const tomorrow=new Date(Date.parse(today+'T12:00Z')+86400000).toISOString().slice(0,10);await sheet.getByLabel('Instance date',{exact:true}).fill(tomorrow);await sheet.getByLabel('Instance time',{exact:true}).fill('15:45');await sheet.getByRole('button',{name:'Save instance',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.reload();assert.equal(await page.getByRole('button',{name:`Edit instance ${routine} moved`,exact:true}).count(),0);await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('heading',{name:'Week at a glance',exact:true}).waitFor();await page.getByRole('button',{name:'This week',exact:true}).click();await page.getByRole('heading',{name:'This week',exact:true}).waitFor();if(!await page.getByRole('button',{name:`View ${tomorrow}`,exact:true}).count())await page.getByRole('button',{name:'Next week',exact:true}).click();await page.getByRole('button',{name:`View ${tomorrow}`,exact:true}).click();await page.getByRole('button',{name:`Edit instance ${routine} moved`,exact:true}).waitFor();const moved=(await api('/resources/occurrences/'+instance.value.id)).body;assert.equal(moved.value.date,today);assert.equal(moved.value.schedule.time,'15:45');assert.equal(moved.value.durationMinutes,45);assert.deepEqual((await api('/resources/routines/'+routineRow.value.id)).body,routineRow);const sibling=all.find(r=>r.value.id!==instance.value.id);assert.deepEqual((await api('/resources/occurrences/'+sibling.value.id)).body,sibling);checks.push('independent instance date/time/title move persists and groups on actual scheduled day; original slot, template and sibling unchanged');await page.getByRole('link',{name:'Today',exact:true}).click()
 await page.getByRole('button',{name:'Day Notes',exact:false}).click();await sheet.locator('.ProseMirror').fill('Daily persistence '+suffix);await sheet.getByRole('button',{name:'Close planner details',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.reload();await page.getByRole('button',{name:'Day Notes',exact:false}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),new RegExp(suffix));await sheet.locator('.ProseMirror').fill('Edited daily persistence '+suffix);await sheet.getByRole('button',{name:'Close planner details',exact:true}).click();await sheet.waitFor({state:'hidden'});checks.push('day notes persist across reload and existing live-query records save without leaking collection metadata')
 await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByLabel('Week starts on').selectOption('0');await page.getByRole('button',{name:'Save preferences',exact:true}).click();await page.getByRole('status').filter({hasText:'Preferences saved.'}).waitFor();await page.reload();assert.equal(await page.getByLabel('Week starts on').inputValue(),'0');checks.push('preferences persist across reload')

 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:'Day Notes',exact:false}).click();const note=(await api('/resources/periodNotes')).body.items.find(n=>n.value.kind==='day'&&n.value.period.start===today);assert.equal((await api('/commands/period-note','POST',{value:{...note.value,notes:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'External note'}]}]}},expectedRevision:note.revision})).status,200);await sheet.locator('.ProseMirror').fill('Unsaved local note');await sheet.getByRole('button',{name:'Close planner details',exact:true}).click();await sheet.getByRole('alert').filter({hasText:'changed elsewhere'}).waitFor();assert.match(await sheet.locator('.ProseMirror').innerText(),/Unsaved local note/);await Promise.all([page.waitForEvent('dialog').then(d=>d.accept()),sheet.getByRole('button',{name:'Discard draft',exact:true}).click()]);checks.push('stale period-note save preserves draft without overwriting concurrent notes');await page.getByRole('link',{name:'Settings',exact:true}).click()
 const csrfStatus=await page.evaluate(async()=> (await fetch('/api/meos/v1/resources/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status);assert.equal(csrfStatus,403);checks.push('browser missing CSRF write rejected')
 await page.getByRole('button',{name:new RegExp(project)}).click();await sheet.getByRole('button',{name:task,exact:true}).click();const taskRow=(await api('/resources/tasks')).body.items.find(r=>r.value.title===task);const external=await api('/resources/tasks/'+taskRow.value.id,'PUT',{value:{...taskRow.value,title:task+' external'},expectedRevision:taskRow.revision});assert.equal(external.status,200);await sheet.getByLabel('Task name',{exact:true}).fill(task+' draft');await sheet.getByRole('button',{name:'Save changes',exact:true}).click();await sheet.getByRole('alert').filter({hasText:'changed elsewhere'}).waitFor();assert.equal(await sheet.getByLabel('Task name',{exact:true}).inputValue(),task+' draft');assert.equal((await api('/resources/tasks/'+taskRow.value.id)).body.value.title,task+' external');await sheet.getByRole('button',{name:'Close details',exact:true}).click();checks.push('stale task revision rejected without overwrite; unsaved draft preserved')

 await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('button',{name:'Add outcome',exact:true}).click();await sheet.getByLabel('New outcome name').fill('Outcome '+suffix);dropTask=true;dropOutcome=true;await sheet.getByRole('button',{name:'Add to week'}).click();await sheet.getByRole('alert').waitFor();await sheet.getByRole('button',{name:'Add to week'}).click();await sheet.getByText('Your task has been created. Retry to link it to this week.').waitFor();await sheet.getByRole('button',{name:'Add to week'}).click();await sheet.waitFor({state:'hidden'});assert.equal(taskKeys.at(-1),taskKeys.at(-2));assert.equal(outcomeIds.at(-1),outcomeIds.at(-2));assert.equal((await api('/resources/tasks?limit=250')).body.items.filter(r=>r.value.title==='Outcome '+suffix).length,1);checks.push('uncertain outcome task and membership commits retry stable IDs without duplicates')
 await page.getByRole('link',{name:'Settings',exact:true}).click();const currentRoutine=(await api('/resources/routines/'+routineRow.value.id)).body;assert.equal((await api('/resources/routines/'+routineRow.value.id,'PUT',{value:{...currentRoutine.value,recurrenceIntent:{text:'every day',anchorDate:today}},expectedRevision:currentRoutine.revision})).status,200);await page.reload();await page.getByRole('button',{name:new RegExp('^'+routine+' ')}).click();assert.equal(await sheet.getByLabel('Frequency intent',{exact:true}).inputValue(),'every day');await sheet.getByLabel('Frequency intent',{exact:true}).fill('three times a week');await sheet.getByRole('button',{name:'Save routine',exact:true}).click();await sheet.waitFor({state:'hidden'});const changedRule=(await api('/resources/routines/'+routineRow.value.id)).body.value;assert.equal(changedRule.recurrenceIntent.kind,'flexible');assert.equal(changedRule.weekdays,undefined);checks.push('frequency intent editing replaces derived interpretation without legacy weekday controls');await page.getByRole('button',{name:new RegExp(project)}).click();await sheet.getByRole('button',{name:'Archive project',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.getByText('Archived resources',{exact:true}).click();await page.getByRole('button',{name:project,exact:true}).click();await sheet.getByLabel('Project name',{exact:true}).fill(project+' edited archived');await sheet.getByRole('button',{name:'Save changes',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('button',{name:project+' edited archived',exact:true}).waitFor();checks.push('archived project ordinary edits persist rather than re-archiving and dropping draft')
 const secondTab=await context.newPage();await secondTab.goto(origin+'/settings');await secondTab.getByRole('heading',{name:'Settings',exact:true}).waitFor()
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('heading',{name:'Sign in to MeOS'}).waitFor();await secondTab.getByRole('heading',{name:'Sign in to MeOS'}).waitFor();assert.equal(await page.getByText(task,{exact:true}).count(),0);await login(credentials.users[1]);assert.equal(await page.getByText(project,{exact:false}).count(),0);checks.push('logout clears screen and second-user data isolation');await secondTab.getByRole('heading',{name:'Settings',exact:true}).waitFor();assert.equal(await secondTab.getByText(project,{exact:false}).count(),0);checks.push('cross-tab logout and new-owner login fence mounted prior-owner screens');await secondTab.close();const writesBefore=projectWrites;await page.evaluate(()=>localStorage.setItem('meos-auth-generation',crypto.randomUUID()));await page.getByRole('button',{name:'New project',exact:true}).click();await sheet.getByLabel('Project name',{exact:true}).fill('Must not dispatch stale-epoch write');await sheet.getByRole('button',{name:'Create project',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();assert.equal(projectWrites,writesBefore);checks.push('changed shared identity epoch blocks dispatch before queued notification');await context.clearCookies();await page.getByRole('button',{name:'New project',exact:true}).click();await sheet.getByLabel('Project name',{exact:true}).fill('Expired session draft');await sheet.getByRole('button',{name:'Create project',exact:true}).click();await page.getByRole('heading',{name:'Sign in to MeOS'}).waitFor();checks.push('expired session mutation returns to sign-in and removes user-scoped screen')
 fs.writeFileSync('persistence-fixture.json',JSON.stringify({runId:process.env.MEOS_ACCEPTANCE_RUN,project:project+' edited archived',task:task+' external',routine:routine+' moved',today,tomorrow}));assert.deepEqual(errors,[]);fs.mkdirSync('artifacts',{recursive:true});await page.screenshot({path:'artifacts/integration-settings.png',fullPage:true});console.log(JSON.stringify({checks,count:checks.length}));fs.writeFileSync('integration-evidence.json',JSON.stringify({runId:process.env.MEOS_ACCEPTANCE_RUN,checks,count:checks.length},null,2))
}
}catch(e){console.error(String(e),JSON.stringify(operationStatuses.slice(-30)));fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/failure.txt',String(e)+'\n'+errors.join('\n')+'\n'+await page.locator('body').innerText({timeout:2000}).catch(()=>'(body unavailable)'));await page.screenshot({path:'artifacts/integration-failure.png',fullPage:true,timeout:2000}).catch(()=>{});throw e}finally{releaseOld?.();await browser.close();await new Promise(resolve=>server.close(resolve))}
