// SPDX-License-Identifier: Apache-2.0
import assert from 'node:assert/strict'
import fs from 'node:fs'
import https from 'node:https'
import http from 'node:http'
import path from 'node:path'
import {spawnSync} from 'node:child_process'
import {chromium} from 'playwright'
import {createProtectedApiProxy} from '../backend/protected-proxy.mjs'
const origin='https://meos-acceptance.invalid',checks=[],errors=[];let dropComplete=false;const completionKeys=[]
const credentials=JSON.parse(fs.readFileSync('private/synthetic-credentials.json'))
const tls=spawnSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout','/tmp/meos-key.pem','-out','/tmp/meos-cert.pem','-days','1','-subj','/CN=meos-acceptance.invalid'],{stdio:'ignore'});assert.equal(tls.status,0)
const upstream=async request=>{const url=new URL(request.url),body=request.method==='GET'?undefined:Buffer.from(await request.arrayBuffer());return new Promise((resolve,reject)=>{const req=http.request({socketPath:'/run/meos-acceptance-data/server.sock',method:request.method,path:url.pathname+url.search,headers:{...Object.fromEntries(request.headers),Host:url.host}},res=>{const parts=[];res.on('data',p=>parts.push(p));res.on('end',()=>{const headers=new Headers();for(let i=0;i<res.rawHeaders.length;i+=2)headers.append(res.rawHeaders[i],res.rawHeaders[i+1]);resolve(new Response(res.statusCode===204?null:Buffer.concat(parts),{status:res.statusCode,headers}))});res.on('error',reject)});req.on('error',reject);req.end(body)})}
const proxy=createProtectedApiProxy({origin,upstream})
const server=https.createServer({key:fs.readFileSync('/tmp/meos-key.pem'),cert:fs.readFileSync('/tmp/meos-cert.pem')},async(req,res)=>{try{
 const chunks=[];for await(const chunk of req)chunks.push(chunk)
 const request=new Request(origin+req.url,{method:req.method,headers:req.headers,body:chunks.length?Buffer.concat(chunks):undefined});const result=await proxy(request)
 if(req.url==='/api/meos/v1/operations/complete_occurrence'){completionKeys.push(JSON.parse(Buffer.concat(chunks)).idempotencyKey);if(dropComplete&&result?.ok){dropComplete=false;res.writeHead(503,{'Content-Type':'application/json'});res.end('{}');return}}
 if(result){res.writeHead(result.status,{...Object.fromEntries(result.headers),'set-cookie':result.headers.getSetCookie()});res.end(Buffer.from(await result.arrayBuffer()));return}
 if(req.url==='/config.js'){res.setHeader('Content-Type','text/javascript');res.end('window.MEOS_CONFIG={demo:false,timezone:"UTC",apiBase:"/api"}');return}
 const url=new URL(origin+req.url);let file=path.join('dist/client',decodeURIComponent(url.pathname));if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file='dist/client/_shell.html'
 const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2'};res.setHeader('Content-Type',types[path.extname(file)]??'application/octet-stream');res.end(fs.readFileSync(file))
 }catch(e){res.writeHead(500);res.end('Acceptance server failed');errors.push(String(e))}})
await new Promise(resolve=>server.listen(8443,'127.0.0.1',resolve))
const browser=await chromium.launch({executablePath:'/opt/playwright/browsers/chromium-1208/chrome-linux64/chrome',headless:true,args:['--no-sandbox','--no-proxy-server','--host-resolver-rules=MAP meos-acceptance.invalid 127.0.0.1:8443']})
const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1280,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.setDefaultTimeout(12000)
async function login(user){await page.goto(origin+'/settings');await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill(user.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Settings',exact:true}).waitFor()}
const suffix=Date.now().toString(36),project='Project '+suffix,task='Task '+suffix
try{
 await login(credentials.users[0]);checks.push('real browser cookie login and authenticated Settings')
 await page.getByRole('button',{name:'New project',exact:true}).click();const sheet=page.locator('dialog[open]');await sheet.getByLabel('Project name',{exact:true}).fill(project);await sheet.locator('.ProseMirror').fill('Persistent project notes');await sheet.getByRole('button',{name:'Create project',exact:true}).click();await sheet.waitFor({state:'hidden'});checks.push('project and ProseMirror save')
 await page.getByRole('button',{name:new RegExp(project)}).click();await sheet.getByRole('button',{name:'Add task',exact:true}).click();await sheet.getByLabel('Task name',{exact:true}).fill(task);await sheet.getByLabel('Scheduled date',{exact:true}).fill(new Date().toISOString().slice(0,10));await sheet.getByLabel('Time (required when scheduled)',{exact:true}).fill('12:30');await sheet.getByLabel(/^Preferred time/).fill('before lunch');await sheet.locator('.ProseMirror').fill('Persistent task notes');await sheet.getByRole('button',{name:'Create task',exact:true}).click();await sheet.waitFor({state:'hidden'});checks.push('generated create_task operation through existing editor')
 await page.getByRole('link',{name:'Today',exact:true}).click();await page.getByRole('button',{name:'Complete '+task,exact:true}).click();await page.reload();await page.locator('details.completed-tasks summary').click();await page.getByRole('button',{name:'Reopen '+task,exact:true}).waitFor();checks.push('Today completion persists across reload')
 await page.getByRole('link',{name:'Week',exact:true}).click();await page.getByRole('heading',{name:/Week/}).first().waitFor();checks.push('real Week renders')
 await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:new RegExp(project)}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),/Persistent project notes/);await sheet.getByRole('button',{name:task,exact:true}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),/Persistent task notes/);assert.equal(await sheet.getByLabel(/^Preferred time/).inputValue(),'before lunch');await sheet.getByRole('button',{name:'Close details',exact:true}).click();checks.push('project/task notes and preference round trip')

 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const session=await(await fetch('/api/meos/v1/session')).json();const result=await fetch('/api/meos/v1'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrf},body:body===undefined?undefined:JSON.stringify(body)});return {status:result.status,body:await result.json().catch(()=>null)}},{path,method,body})
 const routine='Routine '+suffix
 await page.getByRole('button',{name:'New routine',exact:true}).click();await sheet.getByLabel('Routine name',{exact:true}).fill(routine);for(const day of ['Sunday','Saturday'])await sheet.getByLabel(day,{exact:true}).check();await sheet.getByLabel('Routine time',{exact:true}).fill('11:15');await sheet.getByLabel('Preferred time',{exact:true}).fill('in the morning');await sheet.getByRole('button',{name:'Save routine',exact:true}).click();await sheet.waitFor({state:'hidden'});
 const routineRow=(await api('/resources/routines')).body.items.find(r=>r.value.title===routine)
 const all=(await api('/resources/occurrences?limit=250')).body.items.filter(r=>r.value.routineId===routineRow.value.id);assert.equal(all.length,15);const today=new Date().toISOString().slice(0,10),instance=all.find(r=>r.value.date===today);assert(instance);checks.push('routine editor materializes exactly bounded 15 inclusive slots through today+14')
 await page.getByRole('link',{name:'Today',exact:true}).click();dropComplete=true;await page.getByRole('button',{name:`Complete ${routine} on ${today}`,exact:true}).click();await page.getByRole('alert').filter({hasText:/503|Service could not/}).waitFor();await page.getByRole('button',{name:`Complete ${routine} on ${today}`,exact:true}).click();await page.getByRole('button',{name:`Reopen ${routine} on ${today}`,exact:true}).waitFor();assert.equal(completionKeys.at(-1),completionKeys.at(-2));checks.push('uncertain committed occurrence completion retries same idempotency key')
 await page.getByRole('button',{name:`Edit instance ${routine}`,exact:true}).click();await sheet.getByLabel('Instance name',{exact:true}).fill(routine+' moved');await sheet.getByLabel('Instance time',{exact:true}).fill('15:45');await sheet.getByRole('button',{name:'Save instance',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.reload();await page.getByRole('button',{name:`Edit instance ${routine} moved`,exact:true}).waitFor();const moved=(await api('/resources/occurrences/'+instance.value.id)).body;assert.equal(moved.value.date,today);assert.equal(moved.value.schedule.time,'15:45');assert.deepEqual((await api('/resources/routines/'+routineRow.value.id)).body,routineRow);const sibling=all.find(r=>r.value.id!==instance.value.id);assert.deepEqual((await api('/resources/occurrences/'+sibling.value.id)).body,sibling);checks.push('independent instance move/title persists; stable original slot, template and sibling unchanged')
 await page.getByRole('button',{name:'Day Notes',exact:false}).click();await sheet.locator('.ProseMirror').fill('Daily persistence '+suffix);await sheet.getByRole('button',{name:'Save notes',exact:true}).click();await sheet.waitFor({state:'hidden'});await page.reload();await page.getByRole('button',{name:'Day Notes',exact:false}).click();assert.match(await sheet.locator('.ProseMirror').innerText(),new RegExp(suffix));await sheet.locator('.ProseMirror').fill('Edited daily persistence '+suffix);await sheet.getByRole('button',{name:'Save notes',exact:true}).click();await sheet.waitFor({state:'hidden'});checks.push('day notes persist across reload and existing live-query records save without leaking collection metadata')
 await page.getByRole('link',{name:'Settings',exact:true}).click();await page.getByLabel('Week starts on').selectOption('0');await page.getByRole('button',{name:'Save preferences',exact:true}).click();await page.getByRole('status').filter({hasText:'Preferences saved.'}).waitFor();await page.reload();assert.equal(await page.getByLabel('Week starts on').inputValue(),'0');checks.push('preferences persist across reload')
 const csrfStatus=await page.evaluate(async()=> (await fetch('/api/meos/v1/resources/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status);assert.equal(csrfStatus,403);checks.push('browser missing CSRF write rejected')
 await page.getByRole('button',{name:new RegExp(project)}).click();await sheet.getByRole('button',{name:task,exact:true}).click();const taskRow=(await api('/resources/tasks')).body.items.find(r=>r.value.title===task);const external=await api('/resources/tasks/'+taskRow.value.id,'PUT',{value:{...taskRow.value,title:task+' external'},expectedRevision:taskRow.revision});assert.equal(external.status,200);await sheet.getByLabel('Task name',{exact:true}).fill(task+' draft');await sheet.getByRole('button',{name:'Save changes',exact:true}).click();await sheet.getByRole('alert').filter({hasText:'changed elsewhere'}).waitFor();assert.equal(await sheet.getByLabel('Task name',{exact:true}).inputValue(),task+' draft');assert.equal((await api('/resources/tasks/'+taskRow.value.id)).body.value.title,task+' external');await sheet.getByRole('button',{name:'Close details',exact:true}).click();checks.push('stale task revision rejected without overwrite; unsaved draft preserved')
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('heading',{name:'Sign in to MeOS'}).waitFor();assert.equal(await page.getByText(task,{exact:true}).count(),0);await login(credentials.users[1]);assert.equal(await page.getByText(project,{exact:false}).count(),0);checks.push('logout clears screen and second-user data isolation')
 assert.deepEqual(errors,[]);fs.mkdirSync('artifacts',{recursive:true});await page.screenshot({path:'artifacts/integration-settings.png',fullPage:true});console.log(JSON.stringify({checks,count:checks.length}));fs.writeFileSync('integration-evidence.json',JSON.stringify({runId:process.env.MEOS_ACCEPTANCE_RUN,checks,count:checks.length},null,2))
}catch(e){fs.mkdirSync('artifacts',{recursive:true});await page.screenshot({path:'artifacts/integration-failure.png',fullPage:true});fs.writeFileSync('artifacts/failure.txt',String(e)+'\n'+errors.join('\n')+'\n'+await page.locator('body').innerText());throw e}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
